// Freitext-Prüfungsfragen für die Abschlussprüfung
// Anspruchsvolle Transfer-/Analyse-/Anwendungsfragen mit Schulbezug.
// Format: id = stabiler Schlüssel (für Rotation), modul = Modul-Label,
//         f = Frage, muster = Referenz-Musterlösung (Bewertungsmaßstab).
// Die fünf Bewertungskriterien gelten einheitlich für alle Fragen.
window.QUIZ_FREITEXT_KRITERIEN = [
  'Fachliche Richtigkeit',
  'Vollständigkeit',
  'Praxisbezug',
  'Argumentationsqualität',
  'Bezug zum Schulhund-Einsatz'
];

window.QUIZ_FREITEXT = [

  { id: 'ft-oxytocin-pruefungsangst', modul: 'Wirkmechanismen',
    f: 'Eine Schülerin hat starke Prüfungsangst. Erkläre, wie ein Schulhund über das Oxytocin-System und weitere Wirkmechanismen helfen kann, ihre Angst zu reduzieren, und beschreibe eine konkrete, tierschutzgerechte Umsetzung direkt vor einer Klassenarbeit.',
    muster: 'Oxytocin wird bei Mensch und Tier durch Berührung ausgeschüttet („calm and connecting system“, Kuschel-/Bindungshormon). Es senkt den Stresshormonspiegel (Kortisol), Blutdruck und Herzfrequenz (für mehrere Stunden), hebt die Schmerzgrenze und wirkt angst- und aggressionsmindernd. Vor der Arbeit darf die Schülerin – freiwillig und nur wenn sie keine Angst hat – Körperkontakt mit dem Hund haben, um diesen Effekt zu nutzen. Ergänzend wirken: der Hund als „sichere Basis“/Eisbrecher, Beruhigung über Spiegelneuronen/Stimmungsübertragung, Ablenkung aus der Angstspirale, gestärkte Selbstwirksamkeit. Tierschutzgerechte Umsetzung: 1-Kind-Regel, Streichellandkarte beachten (kein Kopf), kurze Dauer, Hund nimmt freiwillig Kontakt auf und kann jederzeit gehen, Stresssignale beobachten und sofort abbrechen, Ruhezone respektieren. Wichtig: Ein positiver Effekt entsteht nur, wenn die Schülerin angstfrei mit dem Hund umgehen kann.' },

  { id: 'ft-soziale-prozesse', modul: 'Wirkmechanismen',
    f: 'Beschreibe an einem konkreten Unterrichtsbeispiel, wie die Anwesenheit des Schulhundes soziale Prozesse und das Klassenklima beeinflussen kann. Welche realistischen Effekte auf Motivation und Konzentration sind zu erwarten – und wo liegen die Grenzen?',
    muster: 'Mensch und Hund besitzen gleiche „social tools“ (Olbrich); der Hund wirkt als sozialer Katalysator/Eisbrecher → mehr Kommunikation, weniger Aggression, mehr Vertrauen und Zusammengehörigkeit. Beispiel: In einer Gesprächsrunde/Konfliktklärung nimmt der Hund Spannung aus dem Raum, Kinder sprechen offener; gleichzeitig halten sie Regeln (leise, rücksichtsvoll) ein, weil der Hund Ruhe braucht → indirekte Verhaltenssteuerung. Realistische Effekte: höhere Motivation und Selbstwirksamkeit durch Erfolgserlebnisse, bessere Konzentration durch Entspannung/Ruhe, besseres Klassenklima. Grenzen: keine Selbstläufer – Wirkung nur bei angstfreien Kindern, nicht alle profitieren gleich, Allergien/Ängste, Mechanismen können fehlinterpretiert werden, und der Hund darf nicht überfordert oder instrumentalisiert werden.' },

  { id: 'ft-stresssignale-handeln', modul: 'Ausdrucksverhalten',
    f: 'Während einer Interaktion mit drei Kindern zeigt der Hund nacheinander: Züngeln, Gähnen, einen abgewandten Blick und dann ein kurzes Erstarren. Deute diese Signale, bewerte die Situation und beschreibe dein konkretes Vorgehen als Lehrkraft.',
    muster: 'Züngeln, Gähnen und Blick abwenden sind Beschwichtigungs-/Stresssignale, hier als Beschwichtigungskette → der Hund fühlt sich unwohl. Das Erstarren (Freeze) ist eine deutliche Eskalation aus den „4 F“; danach ist jedes Verhalten möglich (auch Flucht oder Angriff) – also ein Warnzeichen für akute Überforderung. Bewertung: Drei Kinder gleichzeitig verletzen die 1-Kind-Regel, der Hund wird vermutlich bedrängt/umzingelt. Vorgehen: Interaktion sofort, aber ruhig abbrechen, Abstand schaffen, dem Hund Rückzug auf seinen Ruheplatz/in die Box ermöglichen, Reize reduzieren. Anschließend reflektieren, warum es dazu kam, und die Regeln mit der Klasse erneut besprechen. Auf keinen Fall „durchziehen“ – der Schulhund soll keinen unnötigen Stress aushalten müssen.' },

  { id: 'ft-gemischte-signale-vkt', modul: 'Ausdrucksverhalten',
    f: 'Ein Kind ruft: „Schau, der Hund macht das Spielgesicht und will spielen!“ Der Hund zeigt zwar eine Vorderkörpertiefstellung, fixiert aber das Gegenüber, hat eine sehr gerade Wirbelsäule und nach vorne gerichtete Ohren. Wie interpretierst du das, und wie reagierst du pädagogisch?',
    muster: 'Das ist trotz Vorderkörpertiefstellung KEINE Spielaufforderung: fixierter Blick, sehr gerade Wirbelsäule und nach vorne/oben gerichtete Ohren sprechen für Anspannung bzw. (drohendes) Ernstverhalten. Eine echte Spielaufforderung erkennt man an abgewandtem Blick, kurviger Wirbelsäule, weichen Bewegungen, Spielgesicht, Pausen und Rollenwechsel. Das ist ein gutes Beispiel dafür, dass dieselbe Verhaltensweise je nach Kontext völlig unterschiedliche Bedeutungen hat. Pädagogisch: das Kind ernst nehmen, aber behutsam korrigieren; mit der Klasse das objektive Lesen üben (Beobachten → Beschreiben → Interpretieren → Diskutieren); kein Spiel forcieren; Abstand schaffen und die Situation entschärfen. Daraus eine Lernchance für hündische Körpersprache machen.' },

  { id: 'ft-klassische-gong', modul: 'Lernverhalten',
    f: 'Beim Schulgong zeigt dein Hund zunehmend Unruhe. Erkläre mithilfe der klassischen Konditionierung, wie es dazu kommen konnte, und entwickle einen konkreten Plan, um den Gong positiv umzukonditionieren.',
    muster: 'Der Gong war zunächst ein neutraler Reiz. Weil er wiederholt kurz vor etwas Unangenehmem auftrat (Lärm, aufspringende Kinder, Trubel), wurde er im Gehirn automatisch und unbewusst damit verknüpft (unerwünschte Verknüpfung) → er löst nun Stress aus. Plan (Gegenkonditionierung): Den Gong zunächst reizarm/leiser darbieten und unmittelbar danach etwas sehr Angenehmes geben (Lieblingsleckerli, Spiel). So sagt der Gong künftig „jetzt kommt etwas Gutes“ voraus. Wichtig: belohnen, BEVOR der Hund Stress zeigt (sonst verstärkt man das unerwünschte Verhalten), kleinschrittig, viele Wiederholungen, Reizstärke nur langsam steigern (Annäherung an die Realbedingungen), niemals Reizüberflutung/Flooding. Timing ist entscheidend.' },

  { id: 'ft-operant-anspringen', modul: 'Lernverhalten',
    f: 'Dein Hund springt Kinder bei der Begrüßung an, weil sie ihn daraufhin streicheln. Analysiere das Verhalten mit der operanten Konditionierung und beschreibe einen kombinierten Trainings- und Managementplan für den Schulalltag.',
    muster: 'Analyse: Anspringen wird positiv verstärkt – das Streicheln ist eine angenehme Konsequenz (Freude) → das Verhalten tritt häufiger auf. Das Matching Law sagt zudem voraus, dass der Hund in den Relationen anspringt, in denen es belohnt wurde. Plan: (1) Management – die Situation so gestalten, dass Anspringen nicht klappt bzw. nicht belohnt wird (Leine/Abstand, Kinder instruieren, sich nicht „belohnend“ verhalten). (2) Alternativverhalten aufbauen (Training): z. B. die Sitzdose – Sitzen statt Hochspringen wird belohnt. (3) Erwünschtes Verhalten rechtzeitig belohnen, solange der Hund es noch zeigt. (4) Nicht schimpfen, denn Aufmerksamkeit kann selbst eine Verstärkung sein. Unerwünschtes Verhalten früh unterbrechen, Abläufe ritualisieren – je seltener die alte Strategie funktioniert, desto schneller setzt sich die neue durch.' },

  { id: 'ft-generalisierung-decke', modul: 'Lernverhalten',
    f: 'Dein Hund zeigt „Geh auf deine Decke“ zu Hause zuverlässig, im Klassenzimmer aber zunächst nicht. Erkläre dies mit dem Prinzip der Generalisierung und beschreibe den Aufbau. Gehe auch darauf ein, wie du die Belohnung über die Zeit gestaltest (Belohnungsrate).',
    muster: 'Verhalten ist anfangs an Ort, Reize und Ablenkung gebunden und wird nicht automatisch generalisiert – „Decke“ im Wohnzimmer heißt nicht „Decke“ überall. Im Klassenzimmer sind Ort, Menschen und Ablenkung völlig anders, deshalb klappt es zunächst nicht. Aufbau: zuerst reizarm/ruhig üben, dann Ablenkungen langsam steigern und in vielen Situationen wiederholen – dabei immer nur EIN Kriterium gleichzeitig erhöhen (z. B. erst Ablenkung, dann Dauer/Distanz). Belohnung: am Anfang hohe Belohnungsrate und nahezu kontinuierlich belohnen, später variabel/intermittierend ausdünnen, aber in schwierigen Situationen weiterhin gut belohnen. Belohnungen variabel und bedürfnisgerecht wählen. Achtung: Verhalten, das nie mehr belohnt wird, wird gelöscht.' },

  { id: 'ft-modelllernen', modul: 'Lernverhalten',
    f: 'Inwiefern spielen „Lernen am Modell“ und Stimmungsübertragung im Schulhund-Einsatz eine Rolle – sowohl beim Hund als auch bei den Schülern? Leite daraus konkrete Konsequenzen für dein eigenes Verhalten als Lehrkraft ab.',
    muster: 'Stimmungsübertragung: Über Spiegelneuronen übertragen und empfangen Mensch und Hund Emotionen. Eine angespannte Lehrkraft oder unruhige Klasse stresst den Hund – und umgekehrt; eine ruhige, souveräne Lehrkraft beruhigt ihn. Bei den Schülern wirkt vor allem das Modelllernen: Sie übernehmen den achtsamen, respektvollen Umgang mit dem Hund von der Lehrkraft als Vorbild. (Echtes Nachahmungslernen beim Hund ist eng definiert – allein durch Beobachtung etwas vorher nicht Gekonntes tun – und im Alltag selten.) Konsequenzen: selbst Ruhe und Sicherheit ausstrahlen, vorhersehbare Abläufe/Rituale schaffen, einen wertschätzenden Umgang vorleben, keine „Zirkusvorstellungen“ (sonst unrealistisches Hundebild), eigene Anspannung regulieren.' },

  { id: 'ft-risiken-erstklasse', modul: 'Recht & Konzept',
    f: 'Du planst den ersten Schulhund-Einsatz in einer 5. Klasse. Welche rechtlichen und organisatorischen Voraussetzungen musst du erfüllen, und mit welchen konkreten Maßnahmen minimierst du Risiken für Sicherheit und Hygiene? Begründe.',
    muster: 'Rechtlich/organisatorisch: Die RiSU ist in Bayern verbindlich (Umgang mit Tieren in Punkt II–3.1; Schulleitung verantwortlich). Nötig sind: Genehmigung der Schulleitung, ein ausgebildetes Mensch-Hund-Team, Einsatz nur unter ständiger Aufsicht, ein Schulhundkonzept und ein Hygieneplan, eine Haftpflicht mit Schulhund-Zusatz, eine Allergie-/Angstabfrage bei den Sorgeberechtigten (grundsätzlich kein Einsatz bei Allergie – Ausnahme nur mit schriftlicher Zustimmung), Gesundheitscheck/Tierarzt (TVT: 4×/Jahr), Einhaltung der Einsatzgrenzen (max. 2–3×/Woche, max. 3–4 Std.) und Mindestalter/soziale Reife. Sicherheit: Regeln einführen und durchsetzen (1 Hund–1 Kind, nie umzingeln/über den Hund beugen, Ruheplatz tabu, Streichellandkarte), Rückzugsort/Box. Hygiene: Händewaschen, Napf täglich bei mind. 60 °C, Stoffzubehör wöchentlich, Vorsicht bei Rohfütterung (Salmonellen). Begründung: Tierschutz und Schülersicherheit – die LMU-Studie 2022 zeigte 50 % problematische und nur 24,1 % harmlose Sitzungen.' },

  { id: 'ft-unterrichtsphasen', modul: 'Gewöhnung & Einsatz',
    f: 'Beschreibe, wie du den Schulhund sinnvoll und tierschutzgerecht in verschiedene Phasen einer Unterrichtsstunde integrieren kannst (z. B. Einstieg, Arbeitsphase, Ergebnissicherung). Welche Phasen eignen sich NICHT? Begründe mit dem Ruhebedürfnis des Hundes.',
    muster: 'Den größten Anteil hat ohnehin die freie Interaktion (der Hund bewegt sich frei und nimmt selbst Kontakt auf). Gezielte Interaktionen kurz und ritualisiert (Start-/Endsignal) halten: Einstieg – aktive Unterrichtsbeteiligung, z. B. der Hund würfelt Aufgaben oder zieht Karten. Arbeitsphase – der Hund ruht auf seiner Decke/in der Ruhezone; evtl. ein einzelnes Kind als ruhige „Vorlese“-Situation. Ergebnissicherung – Materialien bringen o. Ä., aber den Hund NICHT als Belohnung streicheln lassen. Wichtig: Interaktionen kurz und nicht zu oft hintereinander, freiwillig, mit Abstand, jederzeit abbrechbar, und der Hund muss zwischendurch wirklich zur Ruhe kommen können. Ungeeignet: hektische/laute Phasen, Tests/Stresssituationen, Ausnahmesituationen (Feueralarm, Pausengong-Trubel). Begründung: Einsatzgrenzen und das hohe Ruhe-/Schlafbedürfnis; die Schule darf kein reiner „Action-/Party-Ort“ werden.' },

  { id: 'ft-stress-reduzieren', modul: 'Bindung & Stress',
    f: '„Eine der wichtigsten Aufgaben der Schulhundlehrkraft ist es, den Stress für den Hund zu reduzieren.“ Erläutere, warum das so zentral ist, und nenne mindestens vier konkrete Maßnahmen im Schulalltag – jeweils mit Begründung.',
    muster: 'Warum: Nur ein angstfreier, entspannter Hund mit guter Bindung kann dauerhaft die positiven Wirkungen eines Schulhundes hervorrufen. Dauerstress führt über die Erschöpfungsphase zu gesundheitlichen Schäden, erhöhter Aggressionsbereitschaft und geringerer Konzentration – und ist ein Tierschutzproblem. Maßnahmen: (1) ein verlässlicher „sicherer Hafen“/sichere Basis sein – sicher gebundene Hunde zeigen bei Belastung deutlich weniger Stressreaktionen (secure base effect). (2) Vorhersehbare Rituale und Abläufe schaffen – das gibt Sicherheit. (3) Eine Ruhezone, die nie gestört wird, plus Rückzug/Box – der Hund kann sich entziehen. (4) Regeln, die den Hund schützen (nicht umzingeln, Streichellandkarte, 1-Kind-Regel). (5) Stresssignale früh lesen und den Einsatz anpassen/abbrechen; Einsatzdauer und -häufigkeit begrenzen; keine aversive Erziehung (belastet das Bindungskonto). (mind. vier mit Begründung genügen.)' },

  { id: 'ft-du-evidenz-einfuehrung', modul: 'Wirkmechanismen',
    f: 'Wie führst du den Schulhund in einer neuen Klasse als Individuum ein (Du-Evidenz), und warum ist das pädagogisch wertvoll? Beziehe dabei auch Kinder mit kulturell bedingter Distanz oder Angst gegenüber Hunden ein.',
    muster: 'Du-Evidenz bedeutet, ein Tier als „Du“ mit Namen, Charakter, Vorlieben und Gefühlen wahrzunehmen – das schafft eine besondere sozio-emotionale Beziehung und fördert Empathie und Mitgefühl. Einführung: den Hund mit Namen, „Steckbrief“, Vorlieben/Abneigungen, Bedürfnissen und seiner Körpersprache vorstellen; die Schulhundregeln werden zunächst ohne Hund mehrfach besprochen (z. B. mit Stoffhund). Kinder mit Angst oder kultureller Distanz: langsame Annäherung und Aufklärungsarbeit (nicht in allen Kulturen gilt der Hund als Familienmitglied), strikte Freiwilligkeit, kein Zwang, jedes Kind entscheidet über Nähe selbst. Begründung: Biophilie kann sich auch als Angst ausdrücken; eine positive Wirkung entsteht nur, wenn das Kind angstfrei mit dem Hund umgehen kann.' },

  { id: 'ft-umarmen-meideverhalten', modul: 'Ausdrucksverhalten',
    f: 'Ein Kind möchte den Hund umarmen und beugt sich dafür von oben über ihn. Der Hund dreht den Kopf weg, leckt sich über die Schnauze und kneift die Augen zusammen. Bewerte die Situation anhand des Ausdrucksverhaltens und formuliere konkrete Regeln und Handlungen, die das künftig verhindern.',
    muster: 'Die Signale (Kopf wegdrehen, über die Schnauze lecken, Augen zusammenkneifen/Blinzeln) sind Meide- und Beschwichtigungssignale: „So sagt dein Hund Nein“ – der Körperschwerpunkt geht vom Auslöser weg. Sich von oben über den Hund zu beugen und ihn zu umarmen ist für Hunde bedrohlich und unangenehm; es besteht Eskalations-/Bissgefahr (4 F). Bewertung: klarer Regelverstoß (nie über den Hund beugen, nicht umarmen). Handlungen: sofort ruhig eingreifen, dem Kind erklären, warum das für den Hund unangenehm ist; Regeln durchsetzen (1 Hund–1 Hand, Streichellandkarte, nicht beugen/umarmen, der Hund entscheidet über Nähe, Ruheplatz tabu); Beschwichtigungssignale mit der Klasse thematisieren; Kontakt nur mit Abstand und auf „Einladung“ des Hundes.' },

  { id: 'ft-eustress-dosierung', modul: 'Stress',
    f: 'Auch positive Aufregung (Eustress) kann einem Schulhund schaden. Erkläre den Unterschied zwischen Eustress und Disstress und leite daraus begründete Konsequenzen für Häufigkeit und Gestaltung der Einsätze ab.',
    muster: 'Eustress ist eher positiver Stress (Freude, Vorfreude), Disstress entsteht in unangenehmen, schwer bewältigbaren Situationen und kann Angst und Hilflosigkeit auslösen. Beide aktivieren den Körper über Stresshormone; lang anhaltender Eustress kann zu mentaler Erschöpfung bis hin zum Burnout führen, und das Stressgedächtnis verknüpft Reize mit Emotionen. Das heißt: Auch „tolle“, freudige Einsätze sind anstrengend und summieren sich. Konsequenzen: Einsätze klar begrenzen (max. 2–3×/Woche, 1 Einsatz/Tag, max. 3–4 Std.), ausreichend Ruhe-/Erholungsphasen einplanen, Einsätze eher ruhig gestalten (nicht nur „Action“), die individuelle Belastungsgrenze des Hundes beobachten und Stresssignale ernst nehmen. Im schlechtesten Fall startet der Hund sonst jeden Tag etwas gestresster als am Vortag.' }

];
