// Quizfragen pro Modul
// Format: f = Frage, a = Antwortoptionen, k = Index der korrekten Antwort, e = Erklärung
window.QUIZ = {

grundlagen: [
  { f: 'Wie viele Hunde lebten 2024 etwa in Deutschland?', a: ['ca. 5,2 Millionen', 'ca. 10,5 Millionen', 'ca. 15,9 Millionen', 'ca. 21 Millionen'], k: 1, e: '2024 lebten etwa 10,5 Millionen Hunde in Deutschland – in ca. 21 % aller Haushalte. 15,9 Mio. ist die Zahl der Katzen.' },
  { f: 'Was ist über die Fähigkeit von Hunden, menschliche Gesten zu verstehen, bekannt?', a: ['Sie müssen sie mühsam von Wölfen lernen', 'Sie ist genetisch verankert und besser ausgeprägt als bei Wölfen oder Schimpansen', 'Nur speziell trainierte Hunde verstehen Gesten', 'Schimpansen verstehen menschliche Gesten besser'], k: 1, e: 'Studien zeigen: Hunde beherrschen das Verstehen menschlicher Gesten wesentlich besser als Wölfe oder Schimpansen – die Fähigkeit ist genetisch verankert.' },
  { f: 'In wie viel Prozent aller deutschen Haushalte lebten 2024 Hunde?', a: ['ca. 11 %', 'ca. 21 %', 'ca. 33 %', 'ca. 44 %'], k: 1, e: 'In ca. 21 % aller Haushalte lebten Hunde. 44 % aller Haushalte besitzen irgendein Heimtier.' },
  { f: 'Was berichtet der Autor Mohamad Alkhalaf über Hunde in Syrien?', a: ['Hunde gelten dort als heilige Tiere', 'Fast jede Familie hält einen Hund im Haus', 'Hunde dürfen nicht mit ins Wohnhaus; jemanden „einen Hund“ zu nennen gilt als schlimme Beleidigung', 'Hunde werden dort hauptsächlich als Jagdhunde gehalten'], k: 2, e: 'In Syrien gilt man als verrückt, wenn man mit einem Tier spricht; Hunde müssen im Garten bleiben oder ziehen durch die Straßen – und „Hund“ ist eine schlimme Beleidigung.' },
  { f: 'Welche Konsequenz ergibt sich aus den unterschiedlichen Haltungen gegenüber Hunden für den Schulhundeinsatz?', a: ['Der Schulhund sollte nur in höheren Klassen eingesetzt werden', 'Es braucht ggf. eine langsame Annäherung an das Thema und Aufklärungsarbeit', 'Kinder mit Hundeangst müssen die Klasse wechseln', 'Der Schulhund gewöhnt skeptische Kinder automatisch um'], k: 1, e: 'Nicht alle Menschen sind „Hundefans“ – es braucht unter Umständen eine langsame Annäherung an das Thema „Schulhund“ und Aufklärungsarbeit.' },
  { f: 'Welches Tier wurde als erstes domestiziert?', a: ['Die Katze', 'Das Schaf', 'Der Hund', 'Das Pferd'], k: 2, e: 'Der Hund ist das erste domestizierte Tier und seit Jahrtausenden Teil des menschlichen Lebens.' }
],

begriffe: [
  { f: 'Was unterscheidet den Schul(begleit)hund vom Schulbesuchshund?', a: ['Der Schulbegleithund ist kleiner', 'Der Schulbegleithund lebt mit einer Lehrkraft zusammen und begleitet sie regelmäßig als festes Mensch-Hund-Team', 'Der Schulbesuchshund hat eine längere Ausbildung', 'Es gibt keinen Unterschied'], k: 1, e: 'Der Schul(begleit)hund ist der Hund einer pädagogischen Fachkraft, mit der er zusammenlebt – ein festes Mensch-Hund-Team. Schulbesuchshunde begleiten Nichtlehrkräfte meist einmalig in eine Schule.' },
  { f: 'Wer absolviert die Schulhundausbildung?', a: ['Nur der Hund', 'Nur die Lehrkraft', 'Lehrkraft und Hund gemeinsam als Team', 'Die ganze Klasse'], k: 2, e: 'Beide haben zusammen eine Schulhundausbildung absolviert, bevor der Hund in der Schule eingesetzt wird.' },
  { f: 'Ein Hund, der einen Therapeuten bei Ergotherapie-Sitzungen unterstützt, ist ein ...', a: ['Assistenzhund', 'Besuchshund', 'Therapiebegleithund', 'Schulbesuchshund'], k: 2, e: 'Therapiebegleithunde begleiten einen Therapeuten bei seiner Arbeit in einer Einrichtung (Ergotherapie, Logopädie, Psychotherapie ...).' },
  { f: 'Blindenführhunde und Diabeteswarnhunde gehören zu den ...', a: ['Therapiebegleithunden', 'Assistenzhunden', 'Besuchshunden', 'Schulbegleithunden'], k: 1, e: 'Assistenzhunde werden für eine bestimmte Person ausgebildet und begleiten diese in ihrem Alltag.' },
  { f: 'Worauf liegt laut TVT der Fokus der Tiergestützten Pädagogik?', a: ['Auf sportlichen Höchstleistungen', 'Auf prosozialen Fertigkeiten und kognitiven Funktionen', 'Auf der Hundeausbildung', 'Auf medizinischer Therapie'], k: 1, e: 'TGP ist eine zielgerichtete, geplante und strukturierte Intervention – der Fokus liegt auf prosozialen Fertigkeiten und kognitiven Funktionen.' },
  { f: 'Wann wurde der Verein „Schulhunde Bayern e.V.“ gegründet?', a: ['2009', '2017', '2018', '2022'], k: 2, e: '2009 wurde der Arbeitskreis gegründet, 2017 durch Nadine Kleber reaktiviert – die Vereinsgründung „Schulhunde Bayern e.V.“ erfolgte 2018.' },
  { f: 'Was ist der Vereinszweck des Schulhunde Bayern e.V.?', a: ['Verkauf von Schulhundzubehör', 'Förderung, Vernetzung und Qualifizierung der Schulhundearbeit in Bayern', 'Vermittlung von Schulhunden an Schulen', 'Organisation von Hundesport-Turnieren'], k: 1, e: 'Der Vereinszweck ist die Förderung, Vernetzung und Qualifizierung der Schulhundearbeit in Bayern.' }
],

bindung: [
  { f: 'Vor wie vielen Jahren wurde der Wolf zum Hund domestiziert?', a: ['ca. 5.000 Jahren', 'ca. 15.000 Jahren', 'ca. 50.000 Jahren', 'ca. 150.000 Jahren'], k: 1, e: 'Im Zuge der Domestikation wurde der Wolf vor ca. 15.000 Jahren zum Hund entwickelt.' },
  { f: 'Von wem stammt die Bindungstheorie mit „attachment“ und „bonding“?', a: ['Jack Panksepp', 'John Bowlby', 'Aaron Antonovsky', 'E. L. Thorndike'], k: 1, e: 'Die Bindungstheorie stammt von John Bowlby: Bindungsverhalten des Säuglings („attachment“) und elterliches Fürsorgeverhalten („bonding“).' },
  { f: 'Was beschreibt der „secure base effect“?', a: ['Der Hund verteidigt sein Körbchen', 'Der Hund betrachtet den Menschen bei Erkundung und Gefahr als sichere Basis', 'Der Hund braucht einen festen Schlafplatz', 'Der Mensch fühlt sich durch den Hund sicherer'], k: 1, e: 'Bindung liegt vor, wenn der Hund den Menschen individuell erkennt, ihn bei Erkundung und Gefahr als sichere Basis betrachtet und ihn nach Trennung entspannt begrüßt.' },
  { f: 'Wie viel Prozent der erwachsenen Hundehalter können ihren Hund nur unzureichend lesen?', a: ['31 %', '51 %', '71 %', '91 %'], k: 2, e: 'Trotz nachweislich enger Beziehung können 71 % der erwachsenen Hundehalter ihren Gefährten nur unzureichend lesen.' },
  { f: 'Was zeigen sicher gebundene Hunde in Belastungssituationen, wenn ihre Bezugsperson anwesend ist?', a: ['Mehr Aggression', 'Deutlich weniger Stressreaktionen', 'Stärkeres Jagdverhalten', 'Kein verändertes Verhalten'], k: 1, e: 'Sicher gebundene Hunde zeigen in Anwesenheit der Bezugsperson in einer Belastungssituation deutlich weniger Stressreaktionen (Schöberl et al. 2015).' },
  { f: 'Welches Verhältnis von positiven zu negativen Erlebnissen sollte laut Humanpsychologie mindestens bestehen?', a: ['1:1', '2:1', '3:1', '10:1'], k: 2, e: 'Das Verhältnis „Positiv“ zu „Negativ“ sollte nicht kleiner als 3:1 sein – bei Paarbeziehungen spricht man sogar von 5:1.' },
  { f: 'Warum wird auf aversive Erziehung (Strafen) verzichtet?', a: ['Strafen wirken zu schnell', 'Strafregeln sind im wahren Leben nicht einhaltbar, Strafen belasten das Bindungskonto und die Gefahr der Fehlverknüpfung ist zu hoch', 'Strafen sind gesetzlich verboten', 'Hunde vergessen Strafen sofort wieder'], k: 1, e: 'Strafe müsste immer, sofort und heftig erfolgen – das ist nicht einhaltbar. Zudem belasten Strafen das Beziehungskonto, und die Gefahr der Fehlverknüpfung ist viel zu hoch.' }
],

wirkmechanismen: [
  { f: 'Welche der folgenden Wirkungen gehört zu den PHYSIOLOGISCHEN Wirkungen von Schulhunden?', a: ['Verbesserung des Klassenklimas', 'Kommunikationsförderung', 'Senkung von Puls und Blutdruck', 'Erhöhung der Motivation'], k: 2, e: 'Physiologische Wirkungen: Entspannung und Beruhigung (Senkung von Puls, Herzfrequenz, Muskelspannung, Blutdruck) und Erhöhung des Oxytocin-Spiegels.' },
  { f: 'Was bezeichnet Olbrich als „social tools“?', a: ['Spielzeuge für das Training', 'Die gemeinsamen hormonellen und neurologischen Voraussetzungen für soziales Verhalten bei Mensch und Hund', 'Digitale Hilfsmittel für den Unterricht', 'Die Schulhundregeln'], k: 1, e: 'Menschen und Hunde haben die gleichen hormonellen und neurologischen Voraussetzungen für soziales Verhalten – Olbrich nennt sie „social tools“.' },
  { f: 'Wodurch wird Oxytocin ausgeschüttet?', a: ['Durch Futter', 'Durch Berührung', 'Durch Bewegung', 'Durch laute Geräusche'], k: 1, e: 'Das Hormon Oxytocin wird bei Menschen und Tieren durch Berührung ausgeschüttet („calm and connecting system“, Kuschel- und Bindungshormon).' },
  { f: 'Welche Aussage zur Biophilie-Hypothese ist korrekt?', a: ['Alle Menschen mögen automatisch alle Tiere', 'Menschen fühlen sich zu Lebendigem hingezogen – die Verbundenheit kann sich aber auch in Angst ausdrücken', 'Biophilie betrifft nur Kinder', 'Biophilie ist wissenschaftlich widerlegt'], k: 1, e: 'Biophilie meint NICHT, dass alle Menschen alle Tiere mögen – die Verbundenheit kann sich in Wertschätzung, Empathie UND auch in Angst ausdrücken.' },
  { f: 'Was ist das wichtigste Merkmal der Du-Evidenz?', a: ['Das Tier kann sprechen', 'Das Gegenüber, das „Du“, hat einen Namen', 'Das Tier lebt im Haus', 'Das Tier gehorcht aufs Wort'], k: 1, e: 'Wichtiges Merkmal: Das „Du“ hat einen Namen – das hebt das Tier von Artgenossen ab und schafft eine besondere sozio-emotionale Beziehung.' },
  { f: 'Aus welchen 3 Bereichen besteht das Kohärenzgefühl nach Antonovsky?', a: ['Vertrauen, Liebe, Hoffnung', 'Verstehbarkeit, Sinnhaftigkeit, Handhabbarkeit', 'Körper, Geist, Seele', 'Motivation, Konzentration, Disziplin'], k: 1, e: 'Das Kohärenzgefühl besteht aus Verstehbarkeit, Sinnhaftigkeit und Handhabbarkeit.' },
  { f: 'Was sind Spiegelneuronen?', a: ['Nervenzellen, die nur beim Hund vorkommen', 'Die neurobiologische Basis für intuitives Wissen und Empathie', 'Zellen, die Lichtreize verarbeiten', 'Hormone für die Bindung'], k: 1, e: 'Spiegelneuronen erzeugen Bewegungen, Gefühle und Körperzustände des Gegenübers im eigenen Gehirn – die neurobiologische Basis für intuitives Verstehen.' },
  { f: 'Wann kann der positive Oxytocin-Effekt beim Schulhundeinsatz genutzt werden?', a: ['Nur in der Pause', 'Wenn Kinder z. B. vor dem Unterricht Körperkontakt mit dem Hund haben – vorausgesetzt, sie haben keine Angst', 'Nur bei Kindern mit Hundeerfahrung', 'Der Effekt lässt sich nicht nutzen'], k: 1, e: 'Kinder können z. B. vor dem Unterricht Körperkontakt mit dem Hund haben. Ein positiver Effekt ist nur möglich, wenn der Schüler KEINE Angst vor dem Hund hat.' }
],

lernverhalten: [
  { f: 'Was passiert bei der klassischen Konditionierung?', a: ['Der Hund lernt durch Versuch und Irrtum', 'Ein neutraler Reiz bekommt durch Verknüpfung eine Bedeutung', 'Der Hund ahmt andere Hunde nach', 'Der Hund verlernt eine Reaktion'], k: 1, e: 'Klassische Konditionierung: Ein neutraler Reiz bekommt eine Bedeutung (Verknüpfung/Assoziation). Sie erfolgt automatisch, unbewusst und ohne Motivation.' },
  { f: 'Was ist das Grundprinzip der operanten Konditionierung nach Thorndike?', a: ['Hunde lernen nur durch Beobachtung', 'Die Konsequenzen eines Verhaltens beeinflussen sein zukünftiges Auftreten', 'Verhalten ist ausschließlich angeboren', 'Hunde lernen nur mit Clicker'], k: 1, e: 'Lernen durch Versuch und Irrtum: Funktioniert ein Verhalten, wird es häufiger gezeigt; Misserfolge lassen es seltener werden.' },
  { f: '„Etwas Unangenehmes hört auf“ – welcher Quadrant der operanten Konditionierung ist das und welche Emotion löst er aus?', a: ['Positive Strafe – Angst', 'Negative Belohnung – Erleichterung', 'Negative Strafe – Frustration', 'Positive Belohnung – Freude'], k: 1, e: 'Negative Belohnung (Verstärkung): Etwas Unangenehmes hört auf. Emotion: Erleichterung.' },
  { f: 'Was passiert bei der Habituation (Gewöhnung)?', a: ['Der Hund lernt ein neues Signal', 'Der Hund verlernt die Reaktion auf einen ganz bestimmten Reiz', 'Der Hund wird empfindlicher gegenüber Reizen', 'Der Hund lernt durch Nachahmung'], k: 1, e: 'Habituation ist eine Sonderform des Lernens: Es wird nicht etwas Neues gelernt, sondern die Reaktion auf einen bestimmten Reiz verlernt.' },
  { f: 'Was bezeichnet man als „Flooding“?', a: ['Eine effektive Trainingsmethode', 'Die Resignation des Hundes bei Reizüberflutung ohne Entkommen – keine Gewöhnung!', 'Das Schwimmtraining für Hunde', 'Eine Belohnungsform mit viel Futter'], k: 1, e: 'Beim Flooding reagiert der Hund auf die Reizüberflutung mit Resignation und völligem Ausgeliefertsein – ein Entkommen ist nicht möglich. Das ist KEINE Gewöhnung.' },
  { f: 'Ein Hund springt 5 von 10 Besuchern an und wird dabei gestreichelt. Was sagt das Matching Law voraus?', a: ['Er springt nie wieder an', 'Er wird jeden zweiten Menschen anspringen', 'Er springt nur noch Kinder an', 'Er springt jeden Besucher an'], k: 1, e: 'Matching Law: Das Verhalten wird in den Relationen gezeigt, in denen es belohnt wurde – also jeden zweiten Menschen.' },
  { f: 'Was besagt das Premack-Prinzip?', a: ['Belohnungen müssen immer Futter sein', 'Ein wahrscheinliches Verhalten kann als Belohnung für ein unwahrscheinliches Verhalten wirken', 'Strafen wirken besser als Belohnungen', 'Hunde lernen nur in kurzen Einheiten'], k: 1, e: 'Ein mit größerer Wahrscheinlichkeit gezeigtes Verhalten (z. B. Spielen) wirkt als Belohnung für ein mit geringerer Wahrscheinlichkeit gezeigtes (z. B. bei Fuß laufen).' },
  { f: 'Welche drei Trainingskriterien werden im Skript genannt?', a: ['Lob – Leckerli – Spiel', 'Timing – Kriterium – Belohnungsrate', 'Sitz – Platz – Bleib', 'Distanz – Dauer – Ablenkung'], k: 1, e: 'Die Trainingskriterien lauten: Timing – Kriterium – Belohnungsrate.' }
],

markertraining: [
  { f: 'Was bedeutet „Markern“?', a: ['Das Markieren des Reviers', 'Die Ankündigung einer Belohnung – nicht mehr und nicht weniger', 'Ein Abbruchsignal', 'Das Anleinen des Hundes'], k: 1, e: 'Markern bedeutet im Grunde nichts anderes als die Ankündigung einer Belohnung – nicht mehr und nicht weniger.' },
  { f: 'Warum ist das Markersignal ein „Versprechen an den Hund“?', a: ['Weil es nur bei perfektem Verhalten benutzt wird', 'Weil das Markerwort IMMER eine Belohnung ankündigt', 'Weil es täglich wiederholt werden muss', 'Weil nur der Besitzer es benutzen darf'], k: 1, e: 'Das Markerwort kündigt immer eine Belohnung an. Bleibt die Belohnung aus, ist der Click keine zuverlässige Voraussage mehr – die Zusammenarbeit lohnt sich für den Hund nicht mehr.' },
  { f: 'Wie wird das Markerwort konditioniert?', a: ['Click und Leckerchen gleichzeitig zeigen', 'Click → sofort danach Leckerchen, ca. 10× wiederholen, dann testen', 'Erst Leckerchen, dann Click', 'Click nur, wenn der Hund sitzt'], k: 1, e: 'An einem ruhigen Ort: clicken und sofort danach ein Leckerchen geben, ca. 10× wiederholen. Test: Schaut der Hund weg und dreht sich nach dem Click freudig um, ist die Verknüpfung verstanden.' },
  { f: 'Du hast aus Versehen „falsch“ geclickt. Was nun?', a: ['Kein Leckerchen geben, war ja ein Fehler', 'Der Hund bekommt trotzdem seine Belohnung', 'Den Click wiederholen', 'Eine kurze Pause machen und neu anfangen'], k: 1, e: 'Auch wenn man „falsch“ geclickt hat, muss der Hund seine Belohnung bekommen – sonst verliert der Click seine Zuverlässigkeit.' },
  { f: 'Was bedeutet „Capturing“?', a: ['Den Hund einfangen, wenn er wegläuft', 'Spontan angebotenes erwünschtes Verhalten mit dem Marker „einfangen“ und später ein Signal hinzufügen', 'Fotos vom Hund machen', 'Den Hund an der Leine führen'], k: 1, e: 'Capturing („einfangen“): Der Hund bietet ein Verhalten zufällig an, es wird gemarkert – nach einigen Wiederholungen gibt man der Handlung ein Signal.' },
  { f: 'Wann wird ein neues Signal (Hörzeichen) eingeführt?', a: ['Sofort zu Beginn des Trainings', 'Erst wenn der Hund das gewünschte Verhalten zuverlässig zeigen kann', 'Erst nach dem ersten Geburtstag des Hundes', 'Wenn der Hund das Verhalten einmal gezeigt hat'], k: 1, e: 'Ein Signal wird erst eingeführt, wenn der Hund das Verhalten schon zuverlässig zeigt – nur dann zeigt er es später auch auf Signal zuverlässig.' },
  { f: 'Dein Hund kann „Sitz“ im Wohnzimmer. Was bedeutet das für draußen?', a: ['Er kann es automatisch überall', 'Nichts – das Verhalten muss erst in vielen Situationen generalisiert werden', 'Draußen funktionieren Signale grundsätzlich nicht', 'Man braucht draußen ein anderes Wort'], k: 1, e: 'Das Verhalten muss in vielen Situationen und mit unterschiedlichen Ablenkungen generalisiert werden – „Sitz“ im Wohnzimmer heißt nicht „Sitz“ überall.' }
],

belohnungen: [
  { f: 'Welche zwei Grundregeln gelten für Belohnungen?', a: ['Immer Futter, immer sofort', 'Variabel sein und der momentanen Bedürfnislage des Hundes entsprechen', 'Selten und dafür groß belohnen', 'Nur nach perfektem Verhalten belohnen'], k: 1, e: 'Belohnungen sollten variabel sein und der momentanen Bedürfnislage des Hundes so gut es geht entsprechen.' },
  { f: 'Ein ängstlicher Hund traut sich ein paar Schritte auf ein „gruseliges“ Objekt zu. Was ist die passende Belohnung?', a: ['Ein Leckerli direkt am Objekt', 'Distanz zum Objekt geben', 'Lautes Lob', 'Den Hund zum Objekt tragen'], k: 1, e: 'Die Belohnung sollte der Bedürfnislage entsprechen: Der ängstliche Hund wird mit Distanz zum „Gruseligen“ belohnt.' },
  { f: 'Ein Hund lässt sich vom Hasen abrufen. Welche Belohnung passt zur Bedürfnislage?', a: ['Streicheln', 'Ein Hasenfelldummy oder ein geworfener Ball (Hetzmotivation!)', 'Trockenfutter aus der Hand', 'Eine Pause auf der Decke'], k: 1, e: 'Der Hund war in Hetzmotivation – passende Belohnung: Hasenfelldummy geworfen bekommen oder einen Ball hetzen.' },
  { f: 'Welche der folgenden gehört zu den UMWELTBELOHNUNGEN?', a: ['Leberwurst', 'Zerrspiel mit dem Menschen', 'Schnüffeln dürfen / zu Hundefreunden hinrennen', 'Handtouch'], k: 2, e: 'Umweltbelohnungen sind z. B. Schnüffeln, Buddeln, Wälzen, Ableinen, zu Hundefreunden hinrennen, Baden gehen.' },
  { f: 'Welche Praxis-Aufgabe empfiehlt das Skript zu Belohnungen?', a: ['Eine Top-20-Belohnungsliste für den eigenen Hund erstellen', 'Alle Belohnungen abschaffen', 'Nur noch mit Spielzeug belohnen', 'Eine Belohnung pro Woche festlegen'], k: 0, e: 'Im Skript gibt es ein Arbeitsblatt: die eigene Top-20-Belohnungsliste für den eigenen Hund.' }
],

signale: [
  { f: 'Welche zusätzlichen Signale werden für den Schulhundalltag aufgebaut?', a: ['Nur Sitz und Platz', 'Sitzdose, Rückruf, Box-/Deckentraining, Bleib unter Ablenkung, „Aus“ und Seitenwechsel', 'Bellen auf Kommando und Pfote geben', 'Apportieren und Männchen machen'], k: 1, e: 'Ergänzend zum Grundgehorsam: Sitzdose, Rückruf, Box- und Deckentraining, Bleib unter Ablenkung, „Aus“, Seitenwechsel.' },
  { f: 'Wie werden alle Signale grundsätzlich aufgebaut?', a: ['Direkt in der Schule mit der ganzen Klasse', 'Zunächst reizarm in ruhiger Atmosphäre, dann Ablenkungen langsam steigern', 'Mit möglichst vielen Ablenkungen gleichzeitig', 'Nur mit dem Clicker im Klassenzimmer'], k: 1, e: 'Alle Signale werden zunächst reizarm in ruhiger Atmosphäre aufgebaut; Ablenkungen werden langsam gesteigert (Annäherung an schultypische Reize).' },
  { f: 'Was ist die wichtigste Regel bei der Sitzdose?', a: ['Sie muss immer gefüllt sein', 'Sie kündigt ausschließlich Gutes an – niemals schimpfen oder zwingen', 'Sie darf nur die Lehrkraft halten', 'Sie wird nur bei Besuch eingesetzt'], k: 1, e: 'Niemals schimpfen, unfreundlich werden oder den Hund zwingen – die Sitzdose kündigt ausschließlich Gutes an, sonst funktioniert sie nicht.' },
  { f: 'Beim Steigern des Rückrufs gilt:', a: ['Distanz und Ablenkung gleichzeitig steigern', 'Immer nur EIN Kriterium steigern – entweder Distanz oder Ablenkung', 'Immer zuerst die Ablenkung steigern', 'Steigern ist nicht nötig'], k: 1, e: 'Es wird immer nur ein Kriterium gesteigert: entweder Distanz oder Ablenkung.' },
  { f: 'Wie lang ist der Trainingsplan für „Geh auf deine Decke“ angelegt?', a: ['3 Tage', '1 Woche', '3 Wochen', '3 Monate'], k: 2, e: 'Der Trainingsplan umfasst 3 Wochen: Einführung (Woche 1), Verfeinerung und Ablenkungen (Woche 2), Festigung und Integration in den Alltag (Woche 3).' },
  { f: 'Worauf musst du beim Sichtsignal für „Bleib“ achten?', a: ['Die Hand direkt vor den Kopf des Hundes halten', 'Die Hand nur nach oben nehmen und dich nicht über den Hund beugen', 'In die Hocke gehen', 'Mit beiden Händen winken'], k: 1, e: 'Die Hand nicht direkt vor den Kopf des Hundes halten, sondern einfach nach oben nehmen – und sich dabei nicht über den Hund beugen.' },
  { f: 'Was lernt der Hund beim Signal „Aus“?', a: ['Dass ihm Dinge weggenommen werden', 'Dass es sich lohnt, das Objekt seiner Begierde loszulassen bzw. zu tauschen', 'Dass er nichts ins Maul nehmen darf', 'Dass er nur drinnen spielen darf'], k: 1, e: 'Der Hund lernt, dass sich Loslassen/Tauschen lohnt – er wird belohnt und das Objekt wird ihm (erstmal) nicht weggenommen. Achtung: kostet viel Impulskontrolle!' },
  { f: 'Warum ist der Seitenwechsel im Schulgebäude besonders sinnvoll?', a: ['Damit der Hund schneller läuft', 'Für Begegnungen mit Personen im Schulgang', 'Damit der Hund die Treppe findet', 'Für die Pausenaufsicht'], k: 1, e: 'Im Schulgebäude ist der Seitenwechsel sehr sinnvoll, wenn man mit dem Hund durch den Gang läuft und dort Personen begegnet.' },
  { f: 'Was passiert mit Verhalten, das nie mehr belohnt wird?', a: ['Es bleibt für immer bestehen', 'Es wird gelöscht', 'Es wird stärker', 'Es wandelt sich in ein anderes Verhalten'], k: 1, e: 'Denkt daran: Verhalten, das nie mehr belohnt wird, wird gelöscht.' }
],

stress: [
  { f: 'Was ist der Unterschied zwischen Eustress und Disstress?', a: ['Eustress betrifft nur Menschen', 'Eustress ist eher positiver Stress, Disstress entsteht in belastenden, schwer zu bewältigenden Situationen', 'Disstress ist harmlos', 'Es gibt keinen Unterschied'], k: 1, e: 'Eustress entsteht durch positive Einflüsse (z. B. Freude); Disstress entsteht in unangenehmen Situationen, deren Bewältigung nicht oder schwer gelingt.' },
  { f: 'Kann auch Eustress schaden?', a: ['Nein, Eustress ist immer gesund', 'Ja – lang anhaltender Eustress kann zu mentaler Erschöpfung bis hin zum Burnout führen', 'Nur bei Welpen', 'Nur in Kombination mit Disstress'], k: 1, e: '„Lang anhaltender Eustress kann zu mentaler Erschöpfung bis hin zum Burnout führen.“' },
  { f: 'Wie lauten die 3 Phasen einer Stressreaktion in der richtigen Reihenfolge?', a: ['Erschöpfung → Alarm → Widerstand', 'Alarmreaktionsphase → Widerstandsphase → Erschöpfungsphase', 'Widerstand → Alarm → Erholung', 'Anspannung → Entspannung → Erholung'], k: 1, e: 'Alarmreaktionsphase (Stresshormone, Kampf-/Fluchtbereitschaft) → Widerstandsphase (Gleichgewicht wiederherstellen) → Erschöpfungsphase (bei Dauerbelastung).' },
  { f: 'Welche Hormone werden in der Alarmreaktionsphase ausgeschüttet?', a: ['Oxytocin und Serotonin', 'Adrenalin, Noradrenalin und Cortisol', 'Insulin und Glukagon', 'Melatonin und Dopamin'], k: 1, e: 'Der Körper wird durch die Ausschüttung von Stresshormonen wie Adrenalin, Noradrenalin und Cortisol in Alarmbereitschaft versetzt.' },
  { f: '„Reizüberflutung“ und „Entzug von Reizen (Deprivation)“ gehören zu welcher Stressoren-Kategorie?', a: ['Körperliche Stressoren', 'Äußere Stressoren', 'Psychische Stressoren', 'Soziale Stressoren'], k: 1, e: 'Äußere Stressoren: Reizüberflutung, Deprivation, Schmerzreize, Gefahrensituationen, Lärm/Hitze/Nässe, bedrängende Situationen.' },
  { f: 'Welche Merkmale gehören zum „Stressgesicht“?', a: ['Entspannte Lefzen und weicher Blick', 'Erweiterte Pupillen, Ohren nach hinten, Züngeln, Hecheln, zurückgezogene Lefzenwinkel', 'Aufgestellte Rute und gespitzte Ohren', 'Geschlossene Augen'], k: 1, e: 'Stressgesicht: erweiterte Pupillen/Weiß in den Augen, Ohren nach hinten/oben, Züngeln, Muskel-Anspannung um Augen/Maul, Hecheln, vermehrter Speichelfluss, stark zurückgezogene Lefzenwinkel.' },
  { f: 'Was sind Beschwichtigungssignale?', a: ['Signale, mit denen der Hund droht', 'Signale, die beruhigend auf das Gegenüber einwirken sollen – auch Menschen gegenüber', 'Kommandos der Lehrkraft', 'Anzeichen für Krankheit'], k: 1, e: 'Beschwichtigungssignale sollen das Gegenüber beschwichtigen; sie wirken beruhigend, angst- und aggressionsmindernd. Hunde zeigen sie auch Menschen gegenüber.' },
  { f: 'Mehrere Beschwichtigungssignale hintereinander nennt man ...', a: ['Beschwichtigungsketten', 'Signalfolgen', 'Stressspiralen', 'Übersprungshandlungen'], k: 0, e: 'Meist können mehrere Signale hintereinander beobachtet werden – sogenannte Beschwichtigungsketten.' }
],

koerpersprache: [
  { f: 'Wie viele Basisemotionen unterscheidet Jack Panksepp bei allen Säugetieren?', a: ['5', '6', '7', '10'], k: 2, e: 'Jack Panksepp unterteilt die Emotionen in 7 Basisemotionen: Seeking, Fear, Rage, Lust, Care, Panic/Grief, Play.' },
  { f: 'Welche Basisemotion steht für „Erwartung und Vorfreude“?', a: ['Play', 'Seeking', 'Care', 'Rage'], k: 1, e: 'Seeking = Erwartung, Vorfreude. Play = soziale Freude, Care = Fürsorge, Rage = Ärger/Wut.' },
  { f: 'In welcher Reihenfolge solltest du hündisches Verhalten lesen?', a: ['Interpretieren → Beobachten → Beschreiben', 'Beobachten → Beschreiben → Interpretieren → Diskutieren', 'Diskutieren → Interpretieren → Beobachten', 'Beschreiben → Interpretieren → Beobachten'], k: 1, e: 'Erst beobachten und beschreiben – erst danach interpretieren und diskutieren!' },
  { f: 'Woran erkennst du eine Vorderkörpertiefstellung, die KEINE Spielaufforderung ist?', a: ['Blick abgewandt, kurvige Wirbelsäule', 'Augen fokussiert auf das Gegenüber, sehr gerade Wirbelsäule, Ohren nach vorne', 'Weit gespreizte Vorderbeine und „verrücktes“ Gesicht', 'Rute im Bogen nach oben'], k: 1, e: 'Keine Spielaufforderung: Augen fokussiert, Kopf auf das Gegenüber ausgerichtet, Ohren nach vorne/oben, Fang geschlossen, sehr GERADE Wirbelsäule.' },
  { f: 'Welche Merkmale gehören zu echtem Spielverhalten?', a: ['Hohes Tempo ohne Pausen', 'Weiche Bewegungen, Spielgesicht, Play Bow, Pausen, Rollenwechsel, Self-handicapping', 'Fixieren und Beschleichen', 'Steife Körperhaltung'], k: 1, e: 'Merkmale: weiche, fließende Bewegungen; Spielgesicht; Play Bow; Pausen; Rollenwechsel; Self-handicapping.' },
  { f: 'Wie unterscheidet sich sicheres (offensives) von unsicherem (defensivem) Drohen?', a: ['Gar nicht', 'Offensiv: Kopf angehoben, Rute hoch und steif, Beine durchgedrückt – Defensiv: Kopf abgesenkt, Rute eingeklemmt, Körper abgeduckt', 'Offensiv: Hund liegt – Defensiv: Hund steht', 'Offensiv ist leiser als defensiv'], k: 1, e: 'Sicher drohend: alles nach vorne/oben (Kopf oberhalb der Rückenlinie, Rute weit oben, steif, aufrechter Stand). Unsicher drohend: nach hinten/unten (Kopf abgesenkt, Rute eingeklemmt, abgeduckt).' },
  { f: 'Aus wie vielen Bestandteilen besteht die Jagdverhaltenskette?', a: ['3', '5', '7', '9'], k: 2, e: '7 Bestandteile: Orientierung, Fokussieren, Beschleichen, Hetzen, Packen, Töten, Zerlegen & Fressen.' },
  { f: 'Was sind die „4 F“ – die Reaktionen auf eine Bedrohung?', a: ['Futter, Spiel, Schlaf, Flucht', 'Freeze (Einfrieren), Fiddle About (Flirt), Fight (Angriff), Flight (Flucht)', 'Freude, Furcht, Frust, Fürsorge', 'Fressen, Folgen, Flüchten, Freuen'], k: 1, e: 'Die 4 F: Einfrieren/Freeze, Flirt/Fiddle About, Angriff/Fight, Flucht/Flight.' },
  { f: 'Was gilt nach dem Einfrieren (Freeze)?', a: ['Der Hund schläft ein', 'Jedes Verhalten ist möglich', 'Der Hund flieht immer', 'Der Hund greift immer an'], k: 1, e: 'Nach dem Einfrieren ist jedes Verhalten möglich – der Hund befindet sich im Konflikt zwischen Angriff und Flucht.' },
  { f: 'Warum kann eine Leine bei einer Bedrohung problematisch sein?', a: ['Sie reißt zu leicht', 'Sie verhindert die Flucht – dann können andere Strategien der 4 F (z. B. Angriff) zum Einsatz kommen', 'Sie beruhigt den Hund zu stark', 'Sie ist nie problematisch'], k: 1, e: 'Funktioniert die Flucht nicht, z. B. weil der Hund durch eine Leine gehindert wird, können andere Strategien der 4 F zum Einsatz kommen.' }
],

'verhalten-schule': [
  { f: 'Warum ist ein „Nein“ keine Lösung bei unerwünschtem Verhalten?', a: ['Hunde hören schlecht', 'Durch „Nein“ wird Verhalten nur unterdrückt – es kommt an anderen Stellen wieder hervor', 'Hunde verstehen nur englische Kommandos', '„Nein“ ist zu kurz'], k: 1, e: 'Man kann ein Verhalten nicht beibringen, indem man nur „nein“ sagt – unterdrücktes Verhalten kommt an anderen Stellen hervor (Bild vom zugeschweißten Topf).' },
  { f: 'Was solltest du bei wiederholtem unerwünschtem Verhalten als Erstes prüfen?', a: ['Ob der Hund stur ist', 'Gesundheitscheck und Umgebungs-/Stresscheck', 'Ob das Futter zu teuer ist', 'Ob der Hund zu alt ist'], k: 1, e: 'Gesundheitscheck (Schmerzen?) und Umgebungs- & Stresscheck (Schlaf? Entspannung? Veränderungen? Bestimmte Orte/Zeiten/Menschen?).' },
  { f: 'Was bedeutet „Management“ im Hundetraining?', a: ['Die Verwaltung der Schulhunddokumente', 'Veränderung der Rahmenbedingungen, sodass der Hund sich nur wie ein Musterschüler verhalten kann', 'Das Delegieren des Trainings an andere', 'Eine Bestrafungsmethode'], k: 1, e: 'Management = Veränderung der Rahmenbedingungen ohne den Hund zu erschrecken: „Du gestaltest die Situation so, dass dein Hund sich einfach nur wie ein Musterschüler verhalten kann.“' },
  { f: 'Ersetzt Management das Training?', a: ['Ja, vollständig', 'Nein – es schafft aber die Basis dafür und ist eine wichtige Begleitmaßnahme', 'Nur bei Welpen', 'Training ist generell unnötig'], k: 1, e: 'Management ersetzt kein Training, schafft aber die Basis dafür und ist eine wichtige Begleitmaßnahme.' },
  { f: 'Warum kann Schimpfen ein Verhalten sogar verstärken?', a: ['Weil der Hund Angst bekommt', 'Weil Schimpfen Aufmerksamkeit ist – wenn der Hund Aufmerksamkeit möchte, wird das Verhalten dadurch belohnt', 'Weil Schimpfen wie Lob klingt', 'Schimpfen kann nie verstärken'], k: 1, e: 'Schimpfen kann eine Verstärkung sein, wenn der Hund Aufmerksamkeit möchte und diese durch das Schimpfen bekommt.' },
  { f: 'Was ist ein Beispiel für ein Alternativverhalten?', a: ['Den Hund anleinen', 'Die Sitzdose, damit der Hund in Begrüßungssituationen nicht hochspringt', 'Den Hund ignorieren', 'Lauter sprechen'], k: 1, e: 'Alternativverhalten ersetzt das unerwünschte Verhalten durch eine neue, lohnende Strategie – z. B. Sitzdose statt Hochspringen oder Ruhedecke beim Essen.' },
  { f: 'Was wird für Elternabende empfohlen?', a: ['Den Hund unbedingt mitnehmen', 'Keine Mitnahme des Hundes', 'Den Hund nur die erste Stunde dabei haben', 'Die Eltern entscheiden spontan'], k: 1, e: 'Empfehlung: keine Mitnahme auf Elternabende.' },
  { f: 'Feueralarm, Schulfeste, Pausenhof zur Pausenzeit – wie gehst du mit solchen Situationen um?', a: ['Den Hund langsam daran gewöhnen', 'Der Hund sollte dort nicht dabei sein – solche Situationen sind nicht trainierbar (Management)', 'Der Hund lernt das in der Ausbildung', 'Mit extra vielen Leckerlis arbeiten'], k: 1, e: 'Schulische Ausnahme- und Sondersituationen sowie Orte mit vielen Reizen: Hier sollte der Hund nicht dabei sein – Feueralarm & Co. sind nicht trainierbar.' }
],

'regeln-interaktionen': [
  { f: 'Wann werden die Schulhundregeln mit der Klasse besprochen?', a: ['Beim ersten Besuch des Hundes', 'Ohne Anwesenheit des Hundes, vor dem ersten Besuch, mehrfach', 'Nach dem ersten Zwischenfall', 'Nur am Elternabend'], k: 1, e: 'Die Regeln werden zunächst OHNE Anwesenheit des Schulhundes vor dem ersten Besuch mehrfach besprochen und die Hintergründe erklärt (z. B. mit Stoffhund).' },
  { f: 'Welche Regel gehört zu den unverzichtbaren Grundregeln?', a: ['2 Kinder pro Hund', 'Auf dem Ruheplatz darf der Hund NIE gestört werden', 'Der Hund darf nur am Kopf gestreichelt werden', 'Der Hund muss jedes Kind begrüßen'], k: 1, e: 'Unverzichtbar: 1 Hund – 1 Kind; Ruheplatz nie stören; nie umzingeln; nie über den Hund beugen; Streichellandkarte beachten (KEIN Streicheln am Kopf).' },
  { f: 'Was passiert, wenn sich eine Klasse nicht an die Schulhundregeln hält?', a: ['Es gibt eine Verwarnung', 'Der Schulhund kann nicht eingesetzt werden', 'Der Hund bekommt einen Maulkorb', 'Die Regeln werden gelockert'], k: 1, e: 'Alle Regeln müssen eingehalten werden. Sonst kann der Schulhund nicht eingesetzt werden – Schulhunde sollen keinen unnötigen Stress aushalten müssen.' },
  { f: 'Welche Interaktionsform nimmt den größten Zeitanteil in der Schulhundarbeit ein?', a: ['Aktive Unterrichtsbeteiligung', 'Die freie Interaktion', 'Interaktionen ohne Unterrichtsbezug', 'Tricktraining'], k: 1, e: 'Die freie Interaktion (der Hund bewegt sich frei im Klassenzimmer und kann Kontakt aufnehmen) nimmt den größten Zeitanteil ein.' },
  { f: 'Was ergab die Bayerische Schulhundstudie 2022 u. a.?', a: ['Alle Interaktionen waren unproblematisch', 'Interaktionen, die Schüler mögen (z. B. Pfote geben), werden von Hunden oft als unangenehm empfunden', 'Hunde lieben es, umzingelt zu werden', 'Die 1-Kind-Regel wurde immer eingehalten'], k: 1, e: 'Die Studie zeigte: Beliebte Interaktionen sind für Hunde oft unangenehm; die 1-Kind-Regel wurde häufig nicht eingehalten; in 2/3 der Einsätze gab es problematische Verhaltensweisen.' },
  { f: 'Wie sollte der Schulhund bei einer Interaktion positioniert werden?', a: ['Mit dem Rücken zur Klasse', 'So, dass er immer die Lehrkraft UND die Schüler sieht', 'In der Box', 'Hinter der Lehrkraft'], k: 1, e: 'Der Hund wird so positioniert, dass er immer Lehrkraft und Schüler sieht. Die Lehrkraft stellt sich nicht hinter den Hund, sondern neben die Schüler.' },
  { f: 'Warum sollen Schüler den Hund NICHT als Belohnung streicheln?', a: ['Aus Hygienegründen', 'Die wenigsten Hunde mögen das während einer Interaktion', 'Damit das Fell sauber bleibt', 'Weil nur die Lehrkraft streicheln darf'], k: 1, e: 'Vermeide es, dass Schüler den Hund als Belohnung streicheln oder tätscheln – die wenigsten Hunde mögen dies während einer Interaktion und lassen es oft nur über sich ergehen.' },
  { f: 'Wann muss eine Interaktion sofort abgebrochen werden?', a: ['Nach genau 5 Minuten', 'Wenn Schüler und/oder Hund Stressanzeichen oder Unwohlsein zeigen', 'Wenn der Gong läutet', 'Wenn die Übung zu einfach ist'], k: 1, e: 'Jede Interaktion muss sofort abgebrochen werden, wenn der Hund (oder Schüler) Anzeichen von Stress oder Unwohlsein zeigt.' },
  { f: 'Warum keine „Zirkusvorstellungen“ mit dem Schulhund?', a: ['Sie sind zu teuer', 'Schüler bekommen sonst ein unrealistisches Bild von Hunden – Nachmachen kann gefährlich werden. Weniger ist mehr!', 'Tricks sind verboten', 'Der Hund könnte zu berühmt werden'], k: 1, e: 'Bei zu vielen ausgefallenen Interaktionen entsteht ein unrealistisches Bild von Hunden – Alltagshunde sind nicht so trainiert, Nachmachen kann zu gefährlichen Situationen führen.' }
],

'recht-konzept': [
  { f: 'Welches Regelwerk regelt den Umgang mit Tieren in bayerischen Schulen verbindlich?', a: ['Das Tierschutzgesetz allein', 'Die RiSU (Richtlinie zur Sicherheit im Unterricht) der KMK – Punkt II–3.1', 'Die Hundeverordnung Bayern', 'Das Schulhundweb'], k: 1, e: 'Die RiSU der Kultusministerkonferenz enthält in Punkt II–3.1 „Umgang mit Tieren“ Ausführungen zum Hundeeinsatz; in Bayern ist sie eine verbindliche Vorschrift für alle Schulen.' },
  { f: 'Wer ist für die Einhaltung der RiSU vor Ort verantwortlich?', a: ['Das Kultusministerium', 'Die Schulleitung', 'Die Eltern', 'Der Hausmeister'], k: 1, e: 'Für die Einhaltung der RiSU – auch im Bereich der HuPäSch – sind die Schulleitungen vor Ort verantwortlich.' },
  { f: 'Unter wessen Aufsicht darf der Schulhund mit Schülern eingesetzt werden?', a: ['Unter Aufsicht eines beliebigen Erwachsenen', 'Ausschließlich unter ständiger Aufsicht der Hundeführerin / des Hundeführers', 'Schüler ab 16 dürfen allein aufpassen', 'Eine Aufsicht ist nicht nötig'], k: 1, e: 'Der Einsatz erfolgt ausschließlich unter ständiger Aufsicht des Hundeführers – ein Einsatz ohne ihn ist nicht zulässig.' },
  { f: 'Wie oft empfiehlt die TVT eine tierärztliche Vorsorgeuntersuchung?', a: ['1× pro Jahr', '2× pro Jahr', '4× pro Jahr', 'Nur bei Krankheit'], k: 2, e: 'Die TVT empfiehlt eine regelmäßige (4×/Jahr) tierärztliche Vorsorgeuntersuchung sowie Tierarztbesuche bei Krankheitsanzeichen.' },
  { f: 'Welche Einsatzhäufigkeit empfiehlt die TVT maximal?', a: ['Täglich, bis zu 8 Stunden', '2–3× pro Woche, max. 1 Einsatz/Tag für max. 3–4 Stunden', '1× pro Monat', '5× pro Woche, 2 Einsätze täglich'], k: 1, e: 'Max. 2–3×/Woche (abhängig von Einsatzform, Alter, Konstitution), max. 1 Einsatz/Tag für max. 3–4 Stunden.' },
  { f: 'Ab welchem Alter sollte ein Hund laut TVT eingesetzt werden?', a: ['Ab 6 Monaten', 'Nach Erreichen der sozialen Reife mit 2–3 Jahren (empfohlen: älter als 18 Monate)', 'Ab dem 5. Lebensjahr', 'Das Alter spielt keine Rolle'], k: 1, e: 'Mindestalter: nach Erreichen der sozialen Reife mit 2–3 Jahren, mindestens in körperlich und geistig ausgereiftem Entwicklungszustand (empfohlen: älter als 18 Monate).' },
  { f: 'Wie viele Sitzungen stufte die LMU-Studie 2022 als problematisch ein?', a: ['10 %', '25,9 %', '50 %', '75 %'], k: 2, e: '50 % problematisch, 25,9 % kritisch, nur 24,1 % harmlos. Nur 40,7 % der Teams hatten eine Schulhundausbildung; in 64,8 % der Klassen wurde der Hund umzingelt.' },
  { f: 'Was fordert die LMU-Studie für jede Schüler-Hund-Interaktion?', a: ['Mehr Tricks', 'Freiwilligkeit des Hundes, Reflexion durch den Besitzer, Reaktion auf (subtile) Anzeichen wie Entzugsverhalten', 'Längere Einsatzzeiten', 'Weniger Dokumentation'], k: 1, e: 'Jede Interaktion muss auf Freiwilligkeit des Hundes basieren und reflektiert werden; der Besitzer muss auf jedes Hundeanzeichen, v. a. Entzugsverhalten, reagieren.' },
  { f: 'Bei wie viel Prozent der gebarften Hunde fand die kanadische Studie Salmonellen?', a: ['5 %', '15 %', '30 %', '60 %'], k: 2, e: 'Bei 30 % der gebarften Hunde wurden Salmonellen gefunden, ohne dass die Hunde selbst erkrankten – eine Infektionsquelle für Kontaktpersonen.' },
  { f: 'Bei welcher Temperatur wird der Hundenapf täglich gereinigt?', a: ['30 °C', '40 °C', 'mind. 60 °C', '90 °C'], k: 2, e: 'Der Hundenapf wird täglich mit mindestens 60 °C warmem Wasser gereinigt und getrocknet; Stoffzubehör wird wöchentlich bei mind. 60 °C gewaschen.' },
  { f: 'Was gilt, wenn in einer Lerngruppe eine Hundeallergie vorliegt?', a: ['Der Einsatz findet trotzdem statt', 'Grundsätzlich kein Einsatz – Ausnahmen nur mit schriftlicher Zustimmung der Sorgeberechtigten', 'Das Kind muss in eine andere Klasse', 'Der Hund trägt dann einen Anzug'], k: 1, e: 'Grundsätzlich erfolgt kein Einsatz bei Allergie in der Lerngruppe. Ausnahmen nur, wenn die Sorgeberechtigten es wünschen und schriftlich zustimmen.' }
],

gewoehnung: [
  { f: 'Wann findet echte Gewöhnung statt?', a: ['Wenn der Hund stark auf den Reiz reagiert', 'Wenn der Hund dem Reiz so ausgesetzt wird, dass er neutral oder minimalst darauf reagiert', 'Wenn der Hund den Reiz täglich erlebt', 'Wenn der Hund müde ist'], k: 1, e: 'Gewöhnung erfolgt nur, wenn der Hund einem Reiz so ausgesetzt wird, dass er neutral oder minimalst darauf reagiert – sonst droht Sensibilisierung.' },
  { f: 'Wie lauten die ersten beiden Schritte der Schulgewöhnung?', a: ['Eigener Unterricht → Pausenhof', 'Besuche des leeren Schulgebäudes → Besuch des „belebteren“ Schulgebäudes', 'Schulfest → Unterricht', 'Klassenzimmer → Turnhalle'], k: 1, e: 'Reihenfolge: leeres Schulgebäude → belebteres Gebäude → reguläre Unterrichtszeit → „trubeligere“ Zeiten → Stunde bei anderer Lehrkraft → eigener Unterricht.' },
  { f: 'Was ist beim ersten Besuch des leeren Schulgebäudes wichtig?', a: ['Der Hund läuft frei durch alle Räume', 'Gassigang vorher; der Hund erkundet in seinem Tempo an lockerer Leine am Geschirr', 'Möglichst viele Kollegen begrüßen den Hund', 'Der Hund bleibt im Auto'], k: 1, e: 'Gassigang vor dem Schulbesuch; der Hund soll sich sicher fühlen und das Gebäude in seinem Tempo in Ruhe erkunden (lockere Leine am Geschirr).' },
  { f: 'Wann solltest du die Schule beim Gewöhnungsbesuch verlassen?', a: ['Wenn der Hund deutlich gestresst ist', 'BEVOR der Hund Stresszeichen zeigt', 'Nach exakt einer Stunde', 'Wenn der Hund einschläft'], k: 1, e: 'Der Hund sollte trubeligeren Situationen nur kurz ausgesetzt werden, und die Schule sollte verlassen werden, bevor er Stresszeichen zeigt.' },
  { f: 'Wo werden die Schulhundregeln besprochen?', a: ['Beim ersten Hundebesuch', 'In Unterrichtsstunden OHNE Hund', 'Auf dem Pausenhof mit Hund', 'Nur schriftlich per Brief'], k: 1, e: 'Die Besprechung der Schulhundregeln erfolgt in den Unterrichtsstunden ohne Hund.' },
  { f: 'Was gehört zur Checkliste für die Einführung eines Schulhundes?', a: ['Nur ein Foto des Hundes', 'U. a. Gesundheitscheck, Genehmigung der Schulleitung, Konzept + Hygieneplan, Haftpflicht mit Schulhund-Zusatz, Eltern-Info mit Allergieabfrage, Schulhundordner', 'Nur die Zustimmung der Klasse', 'Ein Eignungstest beim Hundeverein'], k: 1, e: 'Die Checkliste umfasst: Gesundheitscheck, Gespräch + Genehmigung der Schulleitung, Schulhundkonzept & Hygieneplan, Haftpflicht mit Zusatz, Gewöhnung, Eltern-/Schülerinfo mit Allergieabfrage, Schulhundordner, Verhaltensregeln.' },
  { f: 'Wofür ist die verschließbare Hundebox im Klassenzimmer da?', a: ['Um unerwünschtes Verhalten zu „managen“', 'Für Notfälle – der Hund kann schnell aus der Situation geschickt und kurz geschützt werden', 'Als dauerhafter Schlafplatz', 'Für den Transport'], k: 1, e: 'Die Box ist für Notfälle (Schlägerei, Erbrochenes, giftige Lebensmittel, medizinischer Notfall) – NICHT um den Hund einzusperren und Verhalten zu „managen“.' },
  { f: 'Welche Regel gilt für die Ruhezone des Hundes?', a: ['Dort dürfen Kinder ihn leise streicheln', 'Dort darf er niemals gestört werden – die Zone „gehört“ nur dem Hund', 'Sie wird täglich umgestellt', 'Sie ist nur für den Winter'], k: 1, e: 'Wenn der Hund in seiner Ruhezone ist, darf er dort niemals von Schülern oder Kollegen gestört werden. Diese Zone gehört nur dem Hund.' },
  { f: 'Warum ist ein Arbeitsteppich wichtig?', a: ['Als Dekoration', 'Hunde rutschen auf Schulböden fast immer; er strukturiert und ritualisiert zudem das Setting', 'Damit der Boden sauber bleibt', 'Als Schlafplatz'], k: 1, e: 'Die Teppiche sind sehr wichtig, da Hunde auf Schulböden fast immer rutschen. Zusätzlich helfen sie, das Setting zu strukturieren und zu ritualisieren – das gibt allen Sicherheit.' },
  { f: 'Was ist beim Hundegitter an der Tür unbedingt zu beachten?', a: ['Es muss aus Holz sein', 'Keine Fluchtwege behindern oder versperren', 'Es muss abschließbar sein', 'Es bleibt dauerhaft montiert'], k: 1, e: 'Bitte individuell absprechen und die örtlichen Gegebenheiten prüfen, damit keine Fluchtwege behindert und versperrt werden.' }
]
};
