// Quizfragen pro Modul
// Format: f = Frage, a = Antwortoptionen, k = Index der korrekten Antwort, e = Erklärung
// Möglichst viel Schul- und Alltagsbezug: die Fragen sind in konkrete
// Klassenzimmer-/Schulalltags-Situationen eingebettet (Anwendung statt reiner
// Faktenabfrage). Schwerere Szenariofragen (d: 3) folgen im Block am Dateiende.
window.QUIZ = {

grundlagen: [
  { f: 'Du gestaltest mit deiner Klasse ein Plakat „Haustiere in Deutschland". Wie viele Hunde lebten 2024 etwa in Deutschland?', a: ['ca. 5,2 Millionen', 'ca. 10,5 Millionen', 'ca. 15,9 Millionen', 'ca. 21 Millionen'], k: 1, e: '2024 lebten etwa 10,5 Millionen Hunde in Deutschland – in ca. 21 % aller Haushalte. 15,9 Mio. ist die Zahl der Katzen.' },
  { f: 'Ein Schüler staunt, wie gut dein Hund auf dein Handzeichen reagiert, und fragt, ob Hunde so etwas mühsam lernen müssen. Was stimmt?', a: ['Sie müssen es mühsam von Wölfen lernen', 'Das Verstehen menschlicher Gesten ist genetisch verankert und besser ausgeprägt als bei Wölfen oder Schimpansen', 'Nur speziell trainierte Hunde verstehen Gesten', 'Schimpansen verstehen menschliche Gesten besser'], k: 1, e: 'Studien zeigen: Hunde beherrschen das Verstehen menschlicher Gesten wesentlich besser als Wölfe oder Schimpansen – die Fähigkeit ist genetisch verankert.' },
  { f: 'Im Sachunterricht fragt ein Kind, wie viele Familien überhaupt einen Hund haben. In wie viel Prozent der deutschen Haushalte lebten 2024 Hunde?', a: ['ca. 11 %', 'ca. 21 %', 'ca. 33 %', 'ca. 44 %'], k: 1, e: 'In ca. 21 % aller Haushalte lebten Hunde. 44 % aller Haushalte besitzen irgendein Heimtier.' },
  { f: 'Ein neu zugewandertes Kind reagiert verängstigt auf deinen Schulhund. Was berichtet der Autor Mohamad Alkhalaf über Hunde in Syrien und hilft dir, das einzuordnen?', a: ['Hunde gelten dort als heilige Tiere', 'Fast jede Familie hält einen Hund im Haus', 'Hunde dürfen nicht mit ins Wohnhaus; jemanden „einen Hund“ zu nennen gilt als schlimme Beleidigung', 'Hunde werden dort hauptsächlich als Jagdhunde gehalten'], k: 2, e: 'In Syrien gilt man als verrückt, wenn man mit einem Tier spricht; Hunde müssen im Garten bleiben oder ziehen durch die Straßen – und „Hund“ ist eine schlimme Beleidigung.' },
  { f: 'In deiner Klasse sind mehrere Kinder, in deren Familien Hunde als gefährlich gelten. Welche Konsequenz ziehst du daraus für den Schulhundeinsatz?', a: ['Der Schulhund sollte nur in höheren Klassen eingesetzt werden', 'Es braucht ggf. eine langsame Annäherung an das Thema und Aufklärungsarbeit', 'Kinder mit Hundeangst müssen die Klasse wechseln', 'Der Schulhund gewöhnt skeptische Kinder automatisch um'], k: 1, e: 'Nicht alle Menschen sind „Hundefans“ – es braucht unter Umständen eine langsame Annäherung an das Thema „Schulhund“ und Aufklärungsarbeit.' },
  { f: 'Im Unterricht entsteht die Frage, welches Tier der Mensch als Erstes zähmte. Was ist richtig?', a: ['Die Katze', 'Das Schaf', 'Der Hund', 'Das Pferd'], k: 2, e: 'Der Hund ist das erste domestizierte Tier und seit Jahrtausenden Teil des menschlichen Lebens.' },
  { f: 'Ein eher zurückhaltendes Kind taut auf, sobald dein Hund im Raum ist, und kommt mit anderen ins Gespräch. Welche typische Rolle des Hundes zeigt sich hier?', a: ['Er wirkt als „Eisbrecher" und regt Kontakte und Gespräche an', 'Er ersetzt die Aufgaben der Lehrkraft', 'Er ist ausschließlich ein Nutztier', 'Er muss dafür viele Tricks beherrschen'], k: 0, e: 'Hunde wirken als Eisbrecher – sie regen Gespräche an und ermöglichen Bekanntschaften, bei Kindern wie Erwachsenen.' },
  { f: 'Ein Kollege meint im Lehrerzimmer: „So ein Hund ist doch nur ein Nutztier." Was lässt sich aus dem Skript dazu sagen?', a: ['Hunde sind weltweit reine Nutztiere', 'In westlichen Ländern gelten Hunde v. a. als Haustiere/Familienmitglieder, teils aber auch als Nutztiere – die Sicht ist kulturell verschieden', 'Hunde sind überall Familienmitglieder', 'Das ist gesetzlich einheitlich geregelt'], k: 1, e: 'In westlichen Industrieländern gelten Hunde vor allem als Haustiere/Familienmitglieder, teils auch nur als Nutztiere; in manchen Kulturen werden sie gegessen oder gelten als unrein.' }
],

begriffe: [
  { f: 'Eine Kollegin bringt einmalig den Hund einer Bekannten in ihre Klasse, um über Hunde aufzuklären. Du lebst mit deinem ausgebildeten Hund und nimmst ihn regelmäßig in deinen Unterricht. Was unterscheidet deinen Schul(begleit)hund vom Schulbesuchshund?', a: ['Der Schulbegleithund ist kleiner', 'Der Schulbegleithund lebt mit einer Lehrkraft zusammen und begleitet sie regelmäßig als festes Mensch-Hund-Team', 'Der Schulbesuchshund hat eine längere Ausbildung', 'Es gibt keinen Unterschied'], k: 1, e: 'Der Schul(begleit)hund ist der Hund einer pädagogischen Fachkraft, mit der er zusammenlebt – ein festes Mensch-Hund-Team. Schulbesuchshunde begleiten Nichtlehrkräfte meist einmalig in eine Schule.' },
  { f: 'Eine Mutter fragt am Elternabend, wer eigentlich die Schulhundausbildung absolviert – nur der Hund? Was antwortest du?', a: ['Nur der Hund', 'Nur die Lehrkraft', 'Lehrkraft und Hund gemeinsam als Team', 'Die ganze Klasse'], k: 2, e: 'Beide haben zusammen eine Schulhundausbildung absolviert, bevor der Hund in der Schule eingesetzt wird.' },
  { f: 'Im Kollegium erzählt jemand von einem Hund, der einen Ergotherapeuten bei seinen Sitzungen begleitet. Welcher Begriff trifft zu?', a: ['Assistenzhund', 'Besuchshund', 'Therapiebegleithund', 'Schulbesuchshund'], k: 2, e: 'Therapiebegleithunde begleiten einen Therapeuten bei seiner Arbeit in einer Einrichtung (Ergotherapie, Logopädie, Psychotherapie ...).' },
  { f: 'Ein Schüler hat einen Blindenführhund gesehen und fragt, zu welcher Gruppe Blindenführ- und Diabeteswarnhunde gehören. Richtig ist:', a: ['Therapiebegleithunde', 'Assistenzhunde', 'Besuchshunde', 'Schulbegleithunde'], k: 1, e: 'Assistenzhunde werden für eine bestimmte Person ausgebildet und begleiten diese in ihrem Alltag.' },
  { f: 'Du formulierst für dein Schulhundkonzept das Ziel deiner Arbeit. Worauf liegt laut TVT der Fokus der Tiergestützten Pädagogik?', a: ['Auf sportlichen Höchstleistungen', 'Auf prosozialen Fertigkeiten und kognitiven Funktionen', 'Auf der Hundeausbildung', 'Auf medizinischer Therapie'], k: 1, e: 'TGP ist eine zielgerichtete, geplante und strukturierte Intervention – der Fokus liegt auf prosozialen Fertigkeiten und kognitiven Funktionen.' },
  { f: 'Du recherchierst für dein Konzept die Geschichte des Vereins. Wann wurde „Schulhunde Bayern e.V." gegründet?', a: ['2009', '2017', '2018', '2022'], k: 2, e: '2009 wurde der Arbeitskreis gegründet, 2017 durch Nadine Kleber reaktiviert – die Vereinsgründung „Schulhunde Bayern e.V.“ erfolgte 2018.' },
  { f: 'Eine Kollegin fragt, wofür der Schulhunde Bayern e.V. eigentlich da ist. Was ist sein Vereinszweck?', a: ['Verkauf von Schulhundzubehör', 'Förderung, Vernetzung und Qualifizierung der Schulhundearbeit in Bayern', 'Vermittlung von Schulhunden an Schulen', 'Organisation von Hundesport-Turnieren'], k: 1, e: 'Der Vereinszweck ist die Förderung, Vernetzung und Qualifizierung der Schulhundearbeit in Bayern.' },
  { f: 'Eine pädagogische Fachkraft besucht mit ihrem Hund regelmäßig ein Seniorenheim, hat aber keine therapeutische Ausbildung. Welcher Begriff passt?', a: ['Therapiebegleithund', 'Besuchshund', 'Assistenzhund', 'Schulbegleithund'], k: 1, e: 'Besuchshunde begleiten Menschen ohne therapeutische Ausbildung regelmäßig in Einrichtungen (Altenheime, Kinderheime o. ä.).' },
  { f: 'Du erklärst der Klasse: Tiergestützte Pädagogik ist keine spontane Spielstunde. Welche Beschreibung trifft laut IAHAIO zu?', a: ['Eine zufällige, ungeplante Begegnung mit Tieren', 'Eine zielgerichtete, geplante und strukturierte Intervention durch (qualifizierte) Fachkräfte', 'Reines Hundetraining', 'Eine medizinische Behandlung'], k: 1, e: 'TGP ist eine zielgerichtete, geplante und strukturierte Intervention, angeleitet/durchgeführt von professionellen Pädagogen oder gleich qualifizierten Personen.' }
],

bindung: [
  { f: 'Im Sachunterricht zum Thema „Vom Wolf zum Hund" willst du die Zeitspanne nennen. Vor wie vielen Jahren wurde der Wolf zum Hund domestiziert?', a: ['ca. 5.000 Jahren', 'ca. 15.000 Jahren', 'ca. 50.000 Jahren', 'ca. 150.000 Jahren'], k: 1, e: 'Im Zuge der Domestikation wurde der Wolf vor ca. 15.000 Jahren zum Hund entwickelt.' },
  { f: 'Du erklärst im Konzept, woher der Bindungsbegriff stammt. Von wem stammt die Bindungstheorie mit „attachment" und „bonding"?', a: ['Jack Panksepp', 'John Bowlby', 'Aaron Antonovsky', 'E. L. Thorndike'], k: 1, e: 'Die Bindungstheorie stammt von John Bowlby: Bindungsverhalten des Säuglings („attachment“) und elterliches Fürsorgeverhalten („bonding“).' },
  { f: 'Dein Hund erkundet im Klassenzimmer Neues, vergewissert sich aber immer wieder bei dir und sucht bei Unsicherheit deine Nähe. Welches Phänomen beschreibt das?', a: ['Der Hund verteidigt sein Körbchen', 'Der „secure base effect“ – der Hund nutzt dich bei Erkundung und Gefahr als sichere Basis', 'Der Hund braucht einen festen Schlafplatz', 'Der Mensch fühlt sich durch den Hund sicherer'], k: 1, e: 'Bindung liegt vor, wenn der Hund den Menschen individuell erkennt, ihn bei Erkundung und Gefahr als sichere Basis betrachtet (secure base effect) und ihn nach Trennung entspannt begrüßt.' },
  { f: 'Eine Kollegin meint, erfahrene Hundehalter würden ihre Hunde schon richtig deuten. Wie viel Prozent können ihren Hund laut Skript nur unzureichend lesen?', a: ['31 %', '51 %', '71 %', '91 %'], k: 2, e: 'Trotz nachweislich enger Beziehung können 71 % der erwachsenen Hundehalter ihren Gefährten nur unzureichend lesen.' },
  { f: 'Dein Hund ist in einer lauteren Unterrichtssituation angespannt, wird aber ruhiger, sobald du in seiner Nähe bleibst. Was zeigen sicher gebundene Hunde, wenn ihre Bezugsperson anwesend ist?', a: ['Mehr Aggression', 'Deutlich weniger Stressreaktionen', 'Stärkeres Jagdverhalten', 'Kein verändertes Verhalten'], k: 1, e: 'Sicher gebundene Hunde zeigen in Anwesenheit der Bezugsperson in einer Belastungssituation deutlich weniger Stressreaktionen (Schöberl et al. 2015).' },
  { f: 'Du führst eine „Bilanzliste" über schöne und unschöne gemeinsame Erlebnisse mit deinem Hund. Welches Verhältnis von positiv zu negativ sollte mindestens bestehen?', a: ['1:1', '2:1', '3:1', '10:1'], k: 2, e: 'Das Verhältnis „Positiv“ zu „Negativ“ sollte nicht kleiner als 3:1 sein – bei Paarbeziehungen spricht man sogar von 5:1.' },
  { f: 'Dein Hund hat im Klassenzimmer „etwas angestellt". Warum verzichtest du bewusst auf Strafen?', a: ['Strafen wirken zu schnell', 'Strafregeln sind im wahren Leben nicht einhaltbar, Strafen belasten das Bindungskonto und die Gefahr der Fehlverknüpfung ist zu hoch', 'Strafen sind gesetzlich verboten', 'Hunde vergessen Strafen sofort wieder'], k: 1, e: 'Strafe müsste immer, sofort und heftig erfolgen – das ist nicht einhaltbar. Zudem belasten Strafen das Beziehungskonto, und die Gefahr der Fehlverknüpfung ist viel zu hoch.' },
  { f: 'Eine Referendarin fragt, was die wichtigste Aufgabe einer Schulhundlehrkraft im Alltag ist. Was nennt das Skript?', a: ['Dem Hund möglichst viele Tricks beibringen', 'Den Stress für den Schulhund reduzieren', 'Den Hund möglichst oft einsetzen', 'Den Hund streng erziehen'], k: 1, e: 'Eine der wichtigsten Aufgaben: den Stress für den Schulhund reduzieren – nur ein angstfreier, entspannter Hund mit guter Bindung kann dauerhaft positiv wirken.' },
  { f: 'Du möchtest die Bindung zu deinem Hund gezielt stärken. Welche Maßnahme passt dazu?', a: ['Häufiger strafen', 'Schöne gemeinsame Erlebnisse schaffen, erwünschtes Verhalten einfangen (Capturing) und den Hund lesen lernen', 'Den Hund öfter allein lassen', 'Mehr Gehorsam erzwingen'], k: 1, e: 'Bindung stärken durch schöne gemeinsame Erlebnisse (Bilanzliste), das 101-Dinge-Ding, Capturing erwünschten Verhaltens und das Lesen-Lernen des Hundes.' }
],

wirkmechanismen: [
  { f: 'Ein ruhiges Kind sitzt mit deinem Hund auf der Decke; Puls und Blutdruck sinken. Zu welchem Wirkungsbereich zählt dieser Effekt?', a: ['Verbesserung des Klassenklimas (sozial)', 'Kommunikationsförderung (sozial)', 'Physiologische Wirkung (Senkung von Puls und Blutdruck)', 'Erhöhung der Motivation (psychologisch)'], k: 2, e: 'Physiologische Wirkungen: Entspannung und Beruhigung (Senkung von Puls, Herzfrequenz, Muskelspannung, Blutdruck) und Erhöhung des Oxytocin-Spiegels.' },
  { f: 'Eine Kollegin fragt, warum die Verständigung zwischen Kind und Hund überhaupt „funktioniert". Was bezeichnet Olbrich als „social tools"?', a: ['Spielzeuge für das Training', 'Die gemeinsamen hormonellen und neurologischen Voraussetzungen für soziales Verhalten bei Mensch und Hund', 'Digitale Hilfsmittel für den Unterricht', 'Die Schulhundregeln'], k: 1, e: 'Menschen und Hunde haben die gleichen hormonellen und neurologischen Voraussetzungen für soziales Verhalten – Olbrich nennt sie „social tools“.' },
  { f: 'Du möchtest gezielt den beruhigenden Oxytocin-Effekt im Unterricht nutzen. Wodurch wird Oxytocin ausgeschüttet?', a: ['Durch Futter', 'Durch Berührung', 'Durch Bewegung', 'Durch laute Geräusche'], k: 1, e: 'Das Hormon Oxytocin wird bei Menschen und Tieren durch Berührung ausgeschüttet („calm and connecting system“, Kuschel- und Bindungshormon).' },
  { f: 'Eine Kollegin sagt: „Kinder lieben doch alle Tiere." Welche Aussage zur Biophilie-Hypothese ist korrekt?', a: ['Alle Menschen mögen automatisch alle Tiere', 'Menschen fühlen sich zu Lebendigem hingezogen – die Verbundenheit kann sich aber auch in Angst ausdrücken', 'Biophilie betrifft nur Kinder', 'Biophilie ist wissenschaftlich widerlegt'], k: 1, e: 'Biophilie meint NICHT, dass alle Menschen alle Tiere mögen – die Verbundenheit kann sich in Wertschätzung, Empathie UND auch in Angst ausdrücken.' },
  { f: 'Du stellst der Klasse deinen Hund mit Namen, Vorlieben und Charakter vor. Was ist das wichtigste Merkmal der Du-Evidenz?', a: ['Das Tier kann sprechen', 'Das Gegenüber, das „Du“, hat einen Namen', 'Das Tier lebt im Haus', 'Das Tier gehorcht aufs Wort'], k: 1, e: 'Wichtiges Merkmal: Das „Du“ hat einen Namen – das hebt das Tier von Artgenossen ab und schafft eine besondere sozio-emotionale Beziehung.' },
  { f: 'Im Konzept beschreibst du, wie der Hund zur Gesundheit (Salutogenese) beiträgt. Aus welchen 3 Bereichen besteht das Kohärenzgefühl nach Antonovsky?', a: ['Vertrauen, Liebe, Hoffnung', 'Verstehbarkeit, Sinnhaftigkeit, Handhabbarkeit', 'Körper, Geist, Seele', 'Motivation, Konzentration, Disziplin'], k: 1, e: 'Das Kohärenzgefühl besteht aus Verstehbarkeit, Sinnhaftigkeit und Handhabbarkeit.' },
  { f: 'Dein Hund scheint zu „spüren", wie es einem traurigen Kind geht. Welche neurobiologische Grundlage steckt dahinter?', a: ['Nervenzellen, die nur beim Hund vorkommen', 'Spiegelneuronen – die neurobiologische Basis für intuitives Wissen und Empathie', 'Zellen, die Lichtreize verarbeiten', 'Hormone für die Bindung'], k: 1, e: 'Spiegelneuronen erzeugen Bewegungen, Gefühle und Körperzustände des Gegenübers im eigenen Gehirn – die neurobiologische Basis für intuitives Verstehen.' },
  { f: 'Du planst, den beruhigenden Hundekontakt gezielt einzusetzen. Wann kann der positive Oxytocin-Effekt genutzt werden?', a: ['Nur in der Pause', 'Wenn Kinder z. B. vor dem Unterricht Körperkontakt mit dem Hund haben – vorausgesetzt, sie haben keine Angst', 'Nur bei Kindern mit Hundeerfahrung', 'Der Effekt lässt sich nicht nutzen'], k: 1, e: 'Kinder können z. B. vor dem Unterricht Körperkontakt mit dem Hund haben. Ein positiver Effekt ist nur möglich, wenn der Schüler KEINE Angst vor dem Hund hat.' },
  { f: 'Du ordnest „mehr Motivation und Selbstvertrauen" einem Wirkungsbereich zu. Zu welchem gehört das?', a: ['Soziale Wirkung', 'Psychologische Wirkung', 'Physiologische Wirkung', 'Zu keinem', ], k: 1, e: 'Psychologische Wirkungen: Motivation ↑, Selbstwirksamkeit, Selbstvertrauen/Selbstwertgefühl ↑, Trost, Angsthemmung, „Türöffner/Eisbrecher“, besseres Klassenklima.' },
  { f: 'Ein Kind, das sonst wenig spricht, erzählt dem Hund auf der Decke ganz offen von seinem Wochenende. Welche Wirkung des Schulhundes zeigt sich hier vor allem?', a: ['Eine rein physiologische Wirkung', 'Eine soziale Wirkung (Kommunikationsförderung)', 'Gar keine belegte Wirkung', 'Eine medizinische Heilwirkung'], k: 1, e: 'Soziale Wirkungen sind u. a. Kommunikationsförderung, mehr Aufmerksamkeit, weniger Aggression, mehr Vertrauen und Zusammengehörigkeit.' }
],

lernverhalten: [
  { f: 'Im Klassenzimmer freut sich dein Hund schon beim Rascheln der Leckerli-Dose, bevor überhaupt Futter da ist. Welcher Lernvorgang ist das?', a: ['Lernen durch Versuch und Irrtum', 'Klassische Konditionierung – ein neutraler Reiz bekommt durch Verknüpfung eine Bedeutung', 'Nachahmung', 'Habituation'], k: 1, e: 'Klassische Konditionierung: Ein neutraler Reiz (das Dosengeräusch) bekommt durch Verknüpfung eine Bedeutung. Sie erfolgt automatisch, unbewusst und ohne Motivation.' },
  { f: 'Dein Hund lernt, dass er durch Anstupsen der Türklinke die Klassenzimmertür öffnen kann, und macht es nun öfter. Welches Grundprinzip steckt dahinter?', a: ['Hunde lernen nur durch Beobachtung', 'Operante Konditionierung: Die Konsequenzen eines Verhaltens beeinflussen sein zukünftiges Auftreten', 'Verhalten ist ausschließlich angeboren', 'Hunde lernen nur mit Clicker'], k: 1, e: 'Operante Konditionierung (Thorndike): Funktioniert ein Verhalten, wird es häufiger gezeigt; Misserfolge lassen es seltener werden.' },
  { f: 'Dein Hund zieht an der Leine; sobald er nachgibt, lässt der unangenehme Zug nach. „Etwas Unangenehmes hört auf“ – welcher Quadrant und welche Emotion ist das?', a: ['Positive Strafe – Angst', 'Negative Belohnung – Erleichterung', 'Negative Strafe – Frustration', 'Positive Belohnung – Freude'], k: 1, e: 'Negative Belohnung (Verstärkung): Etwas Unangenehmes hört auf. Emotion: Erleichterung.' },
  { f: 'Dein Hund erschrickt anfangs beim Schulgong, reagiert nach einigen Wochen aber kaum noch darauf. Wie nennt man dieses „Verlernen" der Reaktion?', a: ['Ein neues Signal lernen', 'Habituation (Gewöhnung) – die Reaktion auf einen bestimmten Reiz wird verlernt', 'Sensibilisierung', 'Nachahmung'], k: 1, e: 'Habituation ist eine Sonderform des Lernens: Es wird nicht etwas Neues gelernt, sondern die Reaktion auf einen bestimmten Reiz verlernt.' },
  { f: 'Ein Welpe wird auf einen lauten Wochenmarkt gestellt „damit er sich gewöhnt", kann nicht weg und erstarrt resigniert. Wie heißt das – und ist es Gewöhnung?', a: ['Eine effektive Trainingsmethode', 'Flooding: Resignation bei Reizüberflutung ohne Entkommen – KEINE Gewöhnung', 'Habituation', 'Eine Belohnungsform'], k: 1, e: 'Beim Flooding reagiert der Hund auf die Reizüberflutung mit Resignation und völligem Ausgeliefertsein – ein Entkommen ist nicht möglich. Das ist KEINE Gewöhnung.' },
  { f: 'Dein Hund springt 5 von 10 Besuchern an und wird dabei gestreichelt. Was sagt das Matching Law voraus?', a: ['Er springt nie wieder an', 'Er wird jeden zweiten Menschen anspringen', 'Er springt nur noch Kinder an', 'Er springt jeden Besucher an'], k: 1, e: 'Matching Law: Das Verhalten wird in den Relationen gezeigt, in denen es belohnt wurde – also jeden zweiten Menschen.' },
  { f: 'Dein Hund läuft erst widerwillig bei Fuß, darf danach aber zu seinen Hundefreunden rennen – mit der Zeit läuft er williger. Welches Prinzip nutzt du?', a: ['Belohnungen müssen immer Futter sein', 'Das Premack-Prinzip: ein wahrscheinliches Verhalten belohnt ein unwahrscheinliches', 'Strafen wirken besser als Belohnungen', 'Hunde lernen nur in kurzen Einheiten'], k: 1, e: 'Premack-Prinzip: Ein mit größerer Wahrscheinlichkeit gezeigtes Verhalten (z. B. zu Hundefreunden rennen) wirkt als Belohnung für ein unwahrscheinlicheres (bei Fuß laufen).' },
  { f: 'Beim Training achtest du auf drei zentrale Kriterien. Welche nennt das Skript?', a: ['Lob – Leckerli – Spiel', 'Timing – Kriterium – Belohnungsrate', 'Sitz – Platz – Bleib', 'Distanz – Dauer – Ablenkung'], k: 1, e: 'Die Trainingskriterien lauten: Timing – Kriterium – Belohnungsrate.' },
  { f: 'Rennende, lärmende Kinder kommen am Hund vorbei. Wie nutzt du die klassische Konditionierung präventiv?', a: ['Erst eingreifen, wenn der Hund schon bellt', 'Den Reiz frühzeitig mit etwas Angenehmem verknüpfen (Leckerli/Distanz) – BEVOR der Hund unerwünscht reagiert', 'Den Hund schimpfen', 'Gar nichts tun'], k: 1, e: 'Der Reiz kann mit etwas Angenehmem verknüpft werden – die Belohnung sollte erfolgen, BEVOR der Hund unerwünschtes Verhalten zeigt, sonst wird dieses versehentlich verstärkt.' },
  { f: 'Im Training willst du möglichst im angenehmen Bereich bleiben. In welchem Quadranten der operanten Konditionierung arbeitest du bevorzugt?', a: ['Positive Strafe', 'Positive Verstärkung (positive Belohnung)', 'Negative Strafe', 'Flooding'], k: 1, e: 'Ziel ist, so gut es geht im Bereich der positiven Verstärkung zu bleiben (etwas Angenehmes kommt hinzu, Emotion: Freude).' }
],

markertraining: [
  { f: 'Eine Kollegin fragt dich, was „Markern" eigentlich bedeutet. Was antwortest du?', a: ['Das Markieren des Reviers', 'Die Ankündigung einer Belohnung – nicht mehr und nicht weniger', 'Ein Abbruchsignal', 'Das Anleinen des Hundes'], k: 1, e: 'Markern bedeutet im Grunde nichts anderes als die Ankündigung einer Belohnung – nicht mehr und nicht weniger.' },
  { f: 'Dein Hund vertraut auf den „Klick". Warum ist das Markersignal ein „Versprechen an den Hund"?', a: ['Weil es nur bei perfektem Verhalten benutzt wird', 'Weil das Markerwort IMMER eine Belohnung ankündigt', 'Weil es täglich wiederholt werden muss', 'Weil nur der Besitzer es benutzen darf'], k: 1, e: 'Das Markerwort kündigt immer eine Belohnung an. Bleibt die Belohnung aus, ist der Click keine zuverlässige Voraussage mehr – die Zusammenarbeit lohnt sich für den Hund nicht mehr.' },
  { f: 'Du möchtest deinem Hund das Markerwort neu beibringen. Wie konditionierst du es?', a: ['Click und Leckerchen gleichzeitig zeigen', 'Click → sofort danach Leckerchen, ca. 10× wiederholen, dann testen', 'Erst Leckerchen, dann Click', 'Click nur, wenn der Hund sitzt'], k: 1, e: 'An einem ruhigen Ort: clicken und sofort danach ein Leckerchen geben, ca. 10× wiederholen. Test: Schaut der Hund weg und dreht sich nach dem Click freudig um, ist die Verknüpfung verstanden.' },
  { f: 'Du hast im Training aus Versehen „falsch" geclickt. Was nun?', a: ['Kein Leckerchen geben, war ja ein Fehler', 'Der Hund bekommt trotzdem seine Belohnung', 'Den Click wiederholen', 'Eine kurze Pause machen und neu anfangen'], k: 1, e: 'Auch wenn man „falsch“ geclickt hat, muss der Hund seine Belohnung bekommen – sonst verliert der Click seine Zuverlässigkeit.' },
  { f: 'Dein Hund legt sich von selbst ruhig auf seine Decke; du markerst genau das und gibst dem Verhalten später ein Signal. Wie heißt diese Methode?', a: ['Den Hund einfangen, wenn er wegläuft', 'Capturing – spontan angebotenes Verhalten markern und später ein Signal hinzufügen', 'Fotos vom Hund machen', 'Den Hund an der Leine führen'], k: 1, e: 'Capturing („einfangen“): Der Hund bietet ein Verhalten zufällig an, es wird gemarkert – nach einigen Wiederholungen gibt man der Handlung ein Signal.' },
  { f: 'Dein Hund geht inzwischen zuverlässig auf die Decke. Wann führst du das Hörzeichen „Decke" ein?', a: ['Sofort zu Beginn des Trainings', 'Erst wenn der Hund das Verhalten zuverlässig zeigt', 'Erst nach dem ersten Geburtstag des Hundes', 'Wenn der Hund das Verhalten einmal gezeigt hat'], k: 1, e: 'Ein Signal wird erst eingeführt, wenn der Hund das Verhalten schon zuverlässig zeigt – nur dann zeigt er es später auch auf Signal zuverlässig.' },
  { f: 'Dein Hund kann „Sitz" zuverlässig im Wohnzimmer. Was bedeutet das fürs Klassenzimmer?', a: ['Er kann es automatisch überall', 'Nichts – das Verhalten muss erst in vielen Situationen generalisiert werden', 'Draußen funktionieren Signale grundsätzlich nicht', 'Man braucht draußen ein anderes Wort'], k: 1, e: 'Das Verhalten muss in vielen Situationen und mit unterschiedlichen Ablenkungen generalisiert werden – „Sitz“ im Wohnzimmer heißt nicht „Sitz“ überall.' },
  { f: 'Welches Markerwort ist im Schulalltag am sinnvollsten?', a: ['Ein langes, wechselndes Wort', 'Ein kurzes, knackiges Wort (z. B. „Top", „Klick", „Zack") oder ein Clicker', 'Ein lautes Schimpfwort', 'Gar kein Wort'], k: 1, e: 'Das Markerwort ist ein kurzes, knackiges Wort (z. B. „Top“, „Klick“, „Zack“, „Jep“) oder der Clicker – eine eindeutige gemeinsame Sprache.' },
  { f: 'Du baust das Markerwort auf. Wann genau führst du das Leckerchen zum Hund?', a: ['Schon sichtbar in der Hand, bevor du clickst', 'Erst NACH dem Click – nicht sichtbar in der Hand halten', 'Gleichzeitig mit dem Click', 'Nur wenn der Hund bettelt'], k: 1, e: 'Das Leckerchen wird erst nach dem Click zum Hund geführt – nicht schon sichtbar in der Hand halten; nach jedem Click MUSS eine Belohnung folgen.' }
],

belohnungen: [
  { f: 'Eine Kollegin fragt dich, wie man eigentlich „richtig" belohnt. Welche zwei Grundregeln nennst du?', a: ['Immer Futter, immer sofort', 'Variabel sein und der momentanen Bedürfnislage des Hundes entsprechen', 'Selten und dafür groß belohnen', 'Nur nach perfektem Verhalten belohnen'], k: 1, e: 'Belohnungen sollten variabel sein und der momentanen Bedürfnislage des Hundes so gut es geht entsprechen.' },
  { f: 'Ein ängstlicher Hund traut sich im Schulflur ein paar Schritte auf ein „gruseliges" Objekt zu. Was ist die passende Belohnung?', a: ['Ein Leckerli direkt am Objekt', 'Distanz zum Objekt geben', 'Lautes Lob', 'Den Hund zum Objekt tragen'], k: 1, e: 'Die Belohnung sollte der Bedürfnislage entsprechen: Der ängstliche Hund wird mit Distanz zum „Gruseligen“ belohnt.' },
  { f: 'Dein Hund bricht in Hetzmotivation eine Verfolgung ab und kommt auf Rückruf. Welche Belohnung passt zur Bedürfnislage?', a: ['Streicheln', 'Ein Hasenfelldummy oder ein geworfener Ball (Hetzmotivation!)', 'Trockenfutter aus der Hand', 'Eine Pause auf der Decke'], k: 1, e: 'Der Hund war in Hetzmotivation – passende Belohnung: Hasenfelldummy geworfen bekommen oder einen Ball hetzen.' },
  { f: 'Du erstellst die Belohnungsliste deines Hundes. Welche der folgenden ist eine UMWELTBELOHNUNG?', a: ['Leberwurst', 'Zerrspiel mit dem Menschen', 'Schnüffeln dürfen / zu Hundefreunden hinrennen', 'Handtouch'], k: 2, e: 'Umweltbelohnungen sind z. B. Schnüffeln, Buddeln, Wälzen, Ableinen, zu Hundefreunden hinrennen, Baden gehen.' },
  { f: 'Welche Praxis-Aufgabe empfiehlt das Skript, um die Belohnungen deines Hundes kennenzulernen?', a: ['Eine Top-20-Belohnungsliste für den eigenen Hund erstellen', 'Alle Belohnungen abschaffen', 'Nur noch mit Spielzeug belohnen', 'Eine Belohnung pro Woche festlegen'], k: 0, e: 'Im Skript gibt es ein Arbeitsblatt: die eigene Top-20-Belohnungsliste für den eigenen Hund.' },
  { f: 'Ein Kind möchte deinen Hund nach einer Übung mit Streicheln belohnen. Worauf weist du hin?', a: ['Streicheln ist immer die beste Belohnung', 'Die wenigsten Hunde mögen Streicheln während einer Interaktion – Belohnung muss zur Bedürfnislage passen', 'Streicheln ist verboten', 'Nur am Kopf streicheln'], k: 1, e: 'Was ein Hund als Belohnung empfindet, ist individuell verschieden (z. B. Streicheln!). Belohnungen sollen der momentanen Bedürfnislage entsprechen.' },
  { f: 'Dein Hund liebt es zu schnüffeln und zu suchen. Welche Belohnungsart bietet sich für ihn besonders an?', a: ['Nur Trockenfutter', 'Suchaufgaben (z. B. Dummysuche, Verlorensuche) und Umweltbelohnungen', 'Lautes Lob', 'Strafe vermeiden reicht'], k: 1, e: 'Belohnungskategorien sind u. a. Futter, Objektspiel, Spiel mit dem Menschen, Sozialkontakt, Umweltbelohnungen, gern gezeigte Signale, Suchaufgaben und jagdlicher Kontext – passend zur Vorliebe wählen.' }
],

signale: [
  { f: 'Welche zusätzlichen Signale baust du gezielt für den Schulalltag auf (über den Grundgehorsam hinaus)?', a: ['Nur Sitz und Platz', 'Sitzdose, Rückruf, Box-/Deckentraining, Bleib unter Ablenkung, „Aus“ und Seitenwechsel', 'Bellen auf Kommando und Pfote geben', 'Apportieren und Männchen machen'], k: 1, e: 'Ergänzend zum Grundgehorsam: Sitzdose, Rückruf, Box- und Deckentraining, Bleib unter Ablenkung, „Aus“, Seitenwechsel.' },
  { f: 'Du beginnst, ein neues Signal für den Schulalltag aufzubauen. Wie gehst du grundsätzlich vor?', a: ['Direkt in der Schule mit der ganzen Klasse', 'Zunächst reizarm in ruhiger Atmosphäre, dann Ablenkungen langsam steigern', 'Mit möglichst vielen Ablenkungen gleichzeitig', 'Nur mit dem Clicker im Klassenzimmer'], k: 1, e: 'Alle Signale werden zunächst reizarm in ruhiger Atmosphäre aufgebaut; Ablenkungen werden langsam gesteigert (Annäherung an schultypische Reize).' },
  { f: 'Bei einer Begrüßungssituation setzt du die Sitzdose ein. Was ist dabei die wichtigste Regel?', a: ['Sie muss immer gefüllt sein', 'Sie kündigt ausschließlich Gutes an – niemals schimpfen oder zwingen', 'Sie darf nur die Lehrkraft halten', 'Sie wird nur bei Besuch eingesetzt'], k: 1, e: 'Niemals schimpfen, unfreundlich werden oder den Hund zwingen – die Sitzdose kündigt ausschließlich Gutes an, sonst funktioniert sie nicht.' },
  { f: 'Du steigerst den Rückruf deines Hundes auf dem Pausenhof. Welche Faustregel gilt?', a: ['Distanz und Ablenkung gleichzeitig steigern', 'Immer nur EIN Kriterium steigern – entweder Distanz oder Ablenkung', 'Immer zuerst die Ablenkung steigern', 'Steigern ist nicht nötig'], k: 1, e: 'Es wird immer nur ein Kriterium gesteigert: entweder Distanz oder Ablenkung.' },
  { f: 'Du planst das Training „Geh auf deine Decke". Über welchen Zeitraum ist der Trainingsplan im Skript angelegt?', a: ['3 Tage', '1 Woche', '3 Wochen', '3 Monate'], k: 2, e: 'Der Trainingsplan umfasst 3 Wochen: Einführung (Woche 1), Verfeinerung und Ablenkungen (Woche 2), Festigung und Integration in den Alltag (Woche 3).' },
  { f: 'Beim Sichtsignal für „Bleib" willst du den Hund nicht verunsichern. Worauf achtest du?', a: ['Die Hand direkt vor den Kopf des Hundes halten', 'Die Hand nur nach oben nehmen und sich nicht über den Hund beugen', 'In die Hocke gehen', 'Mit beiden Händen winken'], k: 1, e: 'Die Hand nicht direkt vor den Kopf des Hundes halten, sondern einfach nach oben nehmen – und sich dabei nicht über den Hund beugen.' },
  { f: 'Ein Kind lässt ein Pausenbrot fallen, dein Hund schnappt es. Was soll er beim Signal „Aus" gelernt haben?', a: ['Dass ihm Dinge weggenommen werden', 'Dass es sich lohnt, das Objekt loszulassen bzw. zu tauschen', 'Dass er nichts ins Maul nehmen darf', 'Dass er nur drinnen spielen darf'], k: 1, e: 'Der Hund lernt, dass sich Loslassen/Tauschen lohnt – er wird belohnt und das Objekt wird ihm (erstmal) nicht weggenommen. Achtung: kostet viel Impulskontrolle!' },
  { f: 'Im Schulgang kommt euch eine Gruppe Kinder entgegen. Warum ist gerade hier der Seitenwechsel sinnvoll?', a: ['Damit der Hund schneller läuft', 'Für Begegnungen mit Personen im Schulgang (mehr Abstand, Hund läuft nicht direkt an ihnen)', 'Damit der Hund die Treppe findet', 'Für die Pausenaufsicht'], k: 1, e: 'Im Schulgebäude ist der Seitenwechsel sehr sinnvoll, wenn man mit dem Hund durch den Gang läuft und dort Personen begegnet.' },
  { f: 'Ein früher belohntes Verhalten belohnst du nun nie mehr. Was passiert damit?', a: ['Es bleibt für immer bestehen', 'Es wird gelöscht', 'Es wird stärker', 'Es wandelt sich in ein anderes Verhalten'], k: 1, e: 'Denkt daran: Verhalten, das nie mehr belohnt wird, wird gelöscht.' },
  { f: 'Du baust die Sitzdose mit ansteigenden Ablenkungen auf. Welche Reihenfolge ist sinnvoll?', a: ['Sofort fremde Personen klingeln lassen und die Tür öffnen', 'Erst Familienmitglieder, die herumlaufen, dann Klingeln, dann fremde Personen – langsam steigern', 'Alle Ablenkungen auf einmal', 'Gar keine Ablenkungen einbauen'], k: 1, e: 'Erst nach sicherem Grundverhalten nach und nach Ablenkungen einbauen: Familienmitglieder laufen herum → kommen herein → mit Klingeln → Fremde klingeln ... – langsam steigern.' }
],

stress: [
  { f: 'Dein Hund ist beim Schulfest fröhlich-aufgeregt, an einem anderen Tag dagegen ängstlich-überfordert. Was ist der Unterschied zwischen Eustress und Disstress?', a: ['Eustress betrifft nur Menschen', 'Eustress ist eher positiver Stress, Disstress entsteht in belastenden, schwer zu bewältigenden Situationen', 'Disstress ist harmlos', 'Es gibt keinen Unterschied'], k: 1, e: 'Eustress entsteht durch positive Einflüsse (z. B. Freude); Disstress entsteht in unangenehmen Situationen, deren Bewältigung nicht oder schwer gelingt.' },
  { f: 'Dein Schulhund ist auch an „schönen", aufregenden Tagen sehr aktiv. Kann auch Eustress schaden?', a: ['Nein, Eustress ist immer gesund', 'Ja – lang anhaltender Eustress kann zu mentaler Erschöpfung bis hin zum Burnout führen', 'Nur bei Welpen', 'Nur in Kombination mit Disstress'], k: 1, e: '„Lang anhaltender Eustress kann zu mentaler Erschöpfung bis hin zum Burnout führen.“' },
  { f: 'Dein Hund gerät im Unterricht in eine Stresssituation. Wie lauten die 3 Phasen der Stressreaktion in der richtigen Reihenfolge?', a: ['Erschöpfung → Alarm → Widerstand', 'Alarmreaktionsphase → Widerstandsphase → Erschöpfungsphase', 'Widerstand → Alarm → Erholung', 'Anspannung → Entspannung → Erholung'], k: 1, e: 'Alarmreaktionsphase (Stresshormone, Kampf-/Fluchtbereitschaft) → Widerstandsphase (Gleichgewicht wiederherstellen) → Erschöpfungsphase (bei Dauerbelastung).' },
  { f: 'In der Alarmreaktionsphase wird dein Hund „in Alarmbereitschaft" versetzt. Welche Hormone werden ausgeschüttet?', a: ['Oxytocin und Serotonin', 'Adrenalin, Noradrenalin und Cortisol', 'Insulin und Glukagon', 'Melatonin und Dopamin'], k: 1, e: 'Der Körper wird durch die Ausschüttung von Stresshormonen wie Adrenalin, Noradrenalin und Cortisol in Alarmbereitschaft versetzt.' },
  { f: 'Ein lärmiges Klassenzimmer bedeutet „Reizüberflutung", ein langweiliger Tag im Auto „Entzug von Reizen". Zu welcher Stressoren-Kategorie gehören beide?', a: ['Körperliche Stressoren', 'Äußere Stressoren', 'Psychische Stressoren', 'Soziale Stressoren'], k: 1, e: 'Äußere Stressoren: Reizüberflutung, Deprivation (Reizentzug), Schmerzreize, Gefahrensituationen, Lärm/Hitze/Nässe, bedrängende Situationen.' },
  { f: 'Du beobachtest deinen Hund im Unterricht genau. Welche Merkmale gehören zum „Stressgesicht"?', a: ['Entspannte Lefzen und weicher Blick', 'Erweiterte Pupillen, Ohren nach hinten, Züngeln, Hecheln, zurückgezogene Lefzenwinkel', 'Aufgestellte Rute und gespitzte Ohren', 'Geschlossene Augen'], k: 1, e: 'Stressgesicht: erweiterte Pupillen/Weiß in den Augen, Ohren nach hinten/oben, Züngeln, Muskel-Anspannung um Augen/Maul, Hecheln, vermehrter Speichelfluss, stark zurückgezogene Lefzenwinkel.' },
  { f: 'Dein Hund gähnt und züngelt, als ein Kind sich nähert. Was sind Beschwichtigungssignale?', a: ['Signale, mit denen der Hund droht', 'Signale, die beruhigend auf das Gegenüber einwirken sollen – auch Menschen gegenüber', 'Kommandos der Lehrkraft', 'Anzeichen für Krankheit'], k: 1, e: 'Beschwichtigungssignale sollen das Gegenüber beschwichtigen; sie wirken beruhigend, angst- und aggressionsmindernd. Hunde zeigen sie auch Menschen gegenüber.' },
  { f: 'Dein Hund zeigt nacheinander Gähnen, Lippenlecken und Blick-Abwenden. Wie nennt man mehrere Beschwichtigungssignale hintereinander?', a: ['Beschwichtigungsketten', 'Signalfolgen', 'Stressspiralen', 'Übersprungshandlungen'], k: 0, e: 'Meist können mehrere Signale hintereinander beobachtet werden – sogenannte Beschwichtigungsketten.' },
  { f: 'Jacobs warnt: Folgen stressige Situationen kurz aufeinander, wird die Regulation immer schwerer. Was ist die Folge im schlechtesten Fall?', a: ['Der Hund wird automatisch ruhiger', 'Der Hund startet in jeden neuen Tag etwas gestresster als am Vortag', 'Der Hund vergisst den Stress sofort', 'Nichts passiert'], k: 1, e: '„Im schlechtesten Fall startet der Hund in jeden neuen Tag etwas gestresster als am Vortag.“ Deshalb Erholung und Stressreduktion einplanen.' },
  { f: 'Du bemerkst beim Hund einen staksigen Gang, angelegte Ohren und häufiges Markieren. Wie ordnest du das ein?', a: ['Zeichen von Freude', 'Stressanzeichen am Körper', 'Spielverhalten', 'Hunger'], k: 1, e: 'Stressanzeichen am Körper (sprichhund.de): u. a. angelegte Ohren, durchgedrückte Beine/staksiger Gang, häufiges Urinieren/Markieren, angespannter Körper, Zittern.' }
],

koerpersprache: [
  { f: 'Du erklärst Kolleg:innen die Gefühlswelt von Hunden. Wie viele Basisemotionen unterscheidet Jack Panksepp bei allen Säugetieren?', a: ['5', '6', '7', '10'], k: 2, e: 'Jack Panksepp unterteilt die Emotionen in 7 Basisemotionen: Seeking, Fear, Rage, Lust, Care, Panic/Grief, Play.' },
  { f: 'Dein Hund zeigt freudige Erwartung, als du die Leckerlidose holst. Welche Basisemotion steht für „Erwartung und Vorfreude"?', a: ['Play', 'Seeking', 'Care', 'Rage'], k: 1, e: 'Seeking = Erwartung, Vorfreude. Play = soziale Freude, Care = Fürsorge, Rage = Ärger/Wut.' },
  { f: 'Ein Kind ruft sofort: „Der ist böse!" Welche Reihenfolge solltest du beim Lesen von Hundeverhalten einhalten?', a: ['Interpretieren → Beobachten → Beschreiben', 'Beobachten → Beschreiben → Interpretieren → Diskutieren', 'Diskutieren → Interpretieren → Beobachten', 'Beschreiben → Interpretieren → Beobachten'], k: 1, e: 'Erst beobachten und beschreiben – erst danach interpretieren und diskutieren!' },
  { f: 'Dein Hund zeigt eine Vorderkörpertiefstellung, fixiert aber, hat eine gerade Wirbelsäule und Ohren nach vorn. Woran erkennst du, dass das KEINE Spielaufforderung ist?', a: ['Blick abgewandt, kurvige Wirbelsäule', 'Augen fokussiert auf das Gegenüber, sehr gerade Wirbelsäule, Ohren nach vorne', 'Weit gespreizte Vorderbeine und „verrücktes“ Gesicht', 'Rute im Bogen nach oben'], k: 1, e: 'Keine Spielaufforderung: Augen fokussiert, Kopf auf das Gegenüber ausgerichtet, Ohren nach vorne/oben, Fang geschlossen, sehr GERADE Wirbelsäule.' },
  { f: 'Zwei Hunde toben auf dem Pausenhof. Welche Merkmale sprechen für echtes Spielverhalten?', a: ['Hohes Tempo ohne Pausen', 'Weiche Bewegungen, Spielgesicht, Play Bow, Pausen, Rollenwechsel, Self-handicapping', 'Fixieren und Beschleichen', 'Steife Körperhaltung'], k: 1, e: 'Merkmale: weiche, fließende Bewegungen; Spielgesicht; Play Bow; Pausen; Rollenwechsel; Self-handicapping.' },
  { f: 'Wie unterscheidest du sicheres (offensives) von unsicherem (defensivem) Drohen?', a: ['Gar nicht', 'Offensiv: Kopf angehoben, Rute hoch und steif, Beine durchgedrückt – Defensiv: Kopf abgesenkt, Rute eingeklemmt, Körper abgeduckt', 'Offensiv: Hund liegt – Defensiv: Hund steht', 'Offensiv ist leiser als defensiv'], k: 1, e: 'Sicher drohend: alles nach vorne/oben (Kopf oberhalb der Rückenlinie, Rute weit oben, steif, aufrechter Stand). Unsicher drohend: nach hinten/unten (Kopf abgesenkt, Rute eingeklemmt, abgeduckt).' },
  { f: 'Du erklärst, warum manche Hunde Beute machen. Aus wie vielen Bestandteilen besteht die Jagdverhaltenskette?', a: ['3', '5', '7', '9'], k: 2, e: '7 Bestandteile: Orientierung, Fokussieren, Beschleichen, Hetzen, Packen, Töten, Zerlegen & Fressen.' },
  { f: 'Dein Hund fühlt sich bedroht. Was sind die „4 F" – die möglichen Reaktionen darauf?', a: ['Futter, Spiel, Schlaf, Flucht', 'Freeze (Einfrieren), Fiddle About (Flirt), Fight (Angriff), Flight (Flucht)', 'Freude, Furcht, Frust, Fürsorge', 'Fressen, Folgen, Flüchten, Freuen'], k: 1, e: 'Die 4 F: Einfrieren/Freeze, Flirt/Fiddle About, Angriff/Fight, Flucht/Flight.' },
  { f: 'Dein Hund erstarrt kurz, als ein Kind hektisch auf ihn zustürmt. Was gilt nach dem Einfrieren (Freeze)?', a: ['Der Hund schläft ein', 'Jedes Verhalten ist möglich – der Hund ist im Konflikt zwischen Angriff und Flucht', 'Der Hund flieht immer', 'Der Hund greift immer an'], k: 1, e: 'Nach dem Einfrieren ist jedes Verhalten möglich – der Hund befindet sich im Konflikt zwischen Angriff und Flucht.' },
  { f: 'Dein angeleinter Hund möchte einem Auslöser ausweichen, kann aber nicht weg. Warum kann die Leine hier problematisch sein?', a: ['Sie reißt zu leicht', 'Sie verhindert die Flucht – dann können andere Strategien der 4 F (z. B. Angriff) zum Einsatz kommen', 'Sie beruhigt den Hund zu stark', 'Sie ist nie problematisch'], k: 1, e: 'Funktioniert die Flucht nicht, z. B. weil der Hund durch eine Leine gehindert wird, können andere Strategien der 4 F zum Einsatz kommen.' },
  { f: 'Dein Hund wedelt schmal und sehr schnell mit der Rute. Was bedeutet das eher?', a: ['Große Freude', 'Hohe Körperspannung', 'Einladung zum Spiel', 'Tiefe Entspannung'], k: 1, e: 'Wedeln heißt nicht automatisch Freude: schmal und schnell = hohe Körperspannung; breit/schlackernd = entspannt; kreisend („Propeller“) = Interessenkonflikt.' },
  { f: 'Du möchtest Abweichungen am Verhalten deines Hundes früh erkennen. Was ist die Voraussetzung dafür?', a: ['Man braucht nichts zu kennen', 'Die Neutralhaltung des eigenen Hundes kennen (wie er aussieht, wenn er entspannt ist)', 'Nur die Rute beachten', 'Nur auf Bellen achten'], k: 1, e: 'Um Ausdrucksverhalten richtig zu lesen, musst du wissen, wie der Körper deines Hundes im entspannten Zustand aussieht (Neutralhaltung).' }
],

'verhalten-schule': [
  { f: 'Dein Hund zeigt im Unterricht unerwünschtes Verhalten und du bist versucht, einfach „Nein!" zu sagen. Warum ist das keine Lösung?', a: ['Hunde hören schlecht', 'Durch „Nein“ wird Verhalten nur unterdrückt – es kommt an anderen Stellen wieder hervor', 'Hunde verstehen nur englische Kommandos', '„Nein“ ist zu kurz'], k: 1, e: 'Man kann ein Verhalten nicht beibringen, indem man nur „nein“ sagt – unterdrücktes Verhalten kommt an anderen Stellen hervor (Bild vom zugeschweißten Topf).' },
  { f: 'Dein Hund zeigt im Klassenzimmer plötzlich wiederholt unerwünschtes Verhalten. Was prüfst du als Erstes?', a: ['Ob der Hund stur ist', 'Gesundheitscheck und Umgebungs-/Stresscheck', 'Ob das Futter zu teuer ist', 'Ob der Hund zu alt ist'], k: 1, e: 'Gesundheitscheck (Schmerzen?) und Umgebungs- & Stresscheck (Schlaf? Entspannung? Veränderungen? Bestimmte Orte/Zeiten/Menschen?).' },
  { f: 'Du gestaltest die Situation so, dass dein Hund gar nicht erst zum Mülleimer kommt. Was bedeutet „Management" im Hundetraining?', a: ['Die Verwaltung der Schulhunddokumente', 'Veränderung der Rahmenbedingungen, sodass der Hund sich nur wie ein Musterschüler verhalten kann', 'Das Delegieren des Trainings an andere', 'Eine Bestrafungsmethode'], k: 1, e: 'Management = Veränderung der Rahmenbedingungen ohne den Hund zu erschrecken: „Du gestaltest die Situation so, dass dein Hund sich einfach nur wie ein Musterschüler verhalten kann.“' },
  { f: 'Du nutzt im Schulalltag viel Management (Gitter, Abstand, Decke). Ersetzt Management das Training?', a: ['Ja, vollständig', 'Nein – es schafft aber die Basis dafür und ist eine wichtige Begleitmaßnahme', 'Nur bei Welpen', 'Training ist generell unnötig'], k: 1, e: 'Management ersetzt kein Training, schafft aber die Basis dafür und ist eine wichtige Begleitmaßnahme.' },
  { f: 'Dein Hund bellt, um Aufmerksamkeit zu bekommen, und du schimpfst. Warum kann das das Verhalten sogar verstärken?', a: ['Weil der Hund Angst bekommt', 'Weil Schimpfen Aufmerksamkeit ist – wenn der Hund Aufmerksamkeit möchte, wird das Verhalten dadurch belohnt', 'Weil Schimpfen wie Lob klingt', 'Schimpfen kann nie verstärken'], k: 1, e: 'Schimpfen kann eine Verstärkung sein, wenn der Hund Aufmerksamkeit möchte und diese durch das Schimpfen bekommt.' },
  { f: 'Dein Hund springt Kinder bei der Begrüßung an. Was ist ein gutes Beispiel für ein Alternativverhalten?', a: ['Den Hund anleinen', 'Die Sitzdose, damit der Hund in Begrüßungssituationen nicht hochspringt', 'Den Hund ignorieren', 'Lauter sprechen'], k: 1, e: 'Alternativverhalten ersetzt das unerwünschte Verhalten durch eine neue, lohnende Strategie – z. B. Sitzdose statt Hochspringen oder Ruhedecke beim Essen.' },
  { f: 'Es steht ein Elternabend an. Was wird bezüglich des Schulhundes empfohlen?', a: ['Den Hund unbedingt mitnehmen', 'Keine Mitnahme des Hundes', 'Den Hund nur die erste Stunde dabei haben', 'Die Eltern entscheiden spontan'], k: 1, e: 'Empfehlung: keine Mitnahme auf Elternabende.' },
  { f: 'Feueralarm, Schulfest, Pausenhof zur Pausenzeit – wie gehst du mit solchen Situationen um?', a: ['Den Hund langsam daran gewöhnen', 'Der Hund sollte dort nicht dabei sein – solche Situationen sind nicht trainierbar (Management)', 'Der Hund lernt das in der Ausbildung', 'Mit extra vielen Leckerlis arbeiten'], k: 1, e: 'Schulische Ausnahme- und Sondersituationen sowie Orte mit vielen Reizen: Hier sollte der Hund nicht dabei sein – Feueralarm & Co. sind nicht trainierbar.' },
  { f: 'Ein Schüler klaut nichts vom Tisch, solange du danebenstehst – wartet aber auf unachtsame Momente. Was ist laut Ulrike Seumel der Schlüssel?', a: ['Den Hund streng bestrafen', 'Solange die alte Strategie funktioniert, lernt der Hund nichts Neues – die neue Strategie muss sich für ihn lohnen', 'Den Hund nie mehr in die Küche lassen', 'Das Verhalten ignorieren reicht immer'], k: 1, e: '„Solange die alte Strategie deines Hundes für ihn funktioniert, wird er nichts Neues lernen.“ Die neue Strategie (z. B. auf der Decke warten) muss belohnt werden.' },
  { f: 'Ein Kollege stürmt unangekündigt ins Klassenzimmer und der Hund erschrickt. Wie reagierst du als vorausschauende Lehrkraft am besten?', a: ['Abwarten, was passiert', 'Vorausschauend sein, dem Hund einen Schritt voraus sein und ihn unterstützend durch die Situation führen (Management/Ritual)', 'Den Hund schimpfen', 'Den Kollegen ignorieren'], k: 1, e: 'Vorausschauend handeln, dem Hund einen Schritt voraus sein und ihn unterstützend durch (schwierige) Situationen führen; ritualisierte Abläufe geben Sicherheit.' }
],

'regeln-interaktionen': [
  { f: 'Du bereitest den ersten Schulhundbesuch vor. Wann besprichst du die Schulhundregeln mit der Klasse?', a: ['Beim ersten Besuch des Hundes', 'Ohne Anwesenheit des Hundes, vor dem ersten Besuch, mehrfach', 'Nach dem ersten Zwischenfall', 'Nur am Elternabend'], k: 1, e: 'Die Regeln werden zunächst OHNE Anwesenheit des Schulhundes vor dem ersten Besuch mehrfach besprochen und die Hintergründe erklärt (z. B. mit Stoffhund).' },
  { f: 'Welche Regel gehört zu den unverzichtbaren Grundregeln, die IMMER gelten?', a: ['2 Kinder pro Hund', 'Auf dem Ruheplatz darf der Hund NIE gestört werden', 'Der Hund darf nur am Kopf gestreichelt werden', 'Der Hund muss jedes Kind begrüßen'], k: 1, e: 'Unverzichtbar: 1 Hund – 1 Kind; Ruheplatz nie stören; nie umzingeln; nie über den Hund beugen; Streichellandkarte beachten (KEIN Streicheln am Kopf).' },
  { f: 'Eine Klasse hält sich wiederholt nicht an die Schulhundregeln. Was ist die Konsequenz?', a: ['Es gibt eine Verwarnung', 'Der Schulhund kann nicht eingesetzt werden', 'Der Hund bekommt einen Maulkorb', 'Die Regeln werden gelockert'], k: 1, e: 'Alle Regeln müssen eingehalten werden. Sonst kann der Schulhund nicht eingesetzt werden – Schulhunde sollen keinen unnötigen Stress aushalten müssen.' },
  { f: 'Welche Interaktionsform nimmt im Schulalltag den größten Zeitanteil ein?', a: ['Aktive Unterrichtsbeteiligung', 'Die freie Interaktion', 'Interaktionen ohne Unterrichtsbezug', 'Tricktraining'], k: 1, e: 'Die freie Interaktion (der Hund bewegt sich frei im Klassenzimmer und kann Kontakt aufnehmen) nimmt den größten Zeitanteil ein.' },
  { f: 'Ein Kind möchte dem Hund unbedingt „Pfote geben" lassen, weil es das so süß findet. Was ergab die Bayerische Schulhundstudie 2022 dazu?', a: ['Alle Interaktionen waren unproblematisch', 'Interaktionen, die Schüler mögen (z. B. Pfote geben), werden von Hunden oft als unangenehm empfunden', 'Hunde lieben es, umzingelt zu werden', 'Die 1-Kind-Regel wurde immer eingehalten'], k: 1, e: 'Die Studie zeigte: Beliebte Interaktionen sind für Hunde oft unangenehm; die 1-Kind-Regel wurde häufig nicht eingehalten; in 2/3 der Einsätze gab es problematische Verhaltensweisen.' },
  { f: 'Du machst mit einem Kind eine Übung am Arbeitsteppich. Wie positionierst du den Hund richtig?', a: ['Mit dem Rücken zur Klasse', 'So, dass er immer die Lehrkraft UND die Schüler sieht', 'In der Box', 'Hinter der Lehrkraft'], k: 1, e: 'Der Hund wird so positioniert, dass er immer Lehrkraft und Schüler sieht. Die Lehrkraft stellt sich nicht hinter den Hund, sondern neben die Schüler.' },
  { f: 'Ein Kind will den Hund nach erfolgreicher Übung als Belohnung streicheln. Warum solltest du das vermeiden?', a: ['Aus Hygienegründen', 'Die wenigsten Hunde mögen das während einer Interaktion', 'Damit das Fell sauber bleibt', 'Weil nur die Lehrkraft streicheln darf'], k: 1, e: 'Vermeide es, dass Schüler den Hund als Belohnung streicheln oder tätscheln – die wenigsten Hunde mögen dies während einer Interaktion und lassen es oft nur über sich ergehen.' },
  { f: 'Mitten in einer Übung zeigt der Hund Stressanzeichen. Wann muss die Interaktion abgebrochen werden?', a: ['Nach genau 5 Minuten', 'Sofort, wenn Schüler und/oder Hund Stressanzeichen oder Unwohlsein zeigen', 'Wenn der Gong läutet', 'Wenn die Übung zu einfach ist'], k: 1, e: 'Jede Interaktion muss sofort abgebrochen werden, wenn der Hund (oder Schüler) Anzeichen von Stress oder Unwohlsein zeigt.' },
  { f: 'Eine Kollegin möchte mit dem Hund „beeindruckende Tricks" vorführen. Warum sind „Zirkusvorstellungen" keine gute Idee?', a: ['Sie sind zu teuer', 'Schüler bekommen ein unrealistisches Bild von Hunden – Nachmachen kann gefährlich werden. Weniger ist mehr!', 'Tricks sind verboten', 'Der Hund könnte zu berühmt werden'], k: 1, e: 'Bei zu vielen ausgefallenen Interaktionen entsteht ein unrealistisches Bild von Hunden – Alltagshunde sind nicht so trainiert, Nachmachen kann zu gefährlichen Situationen führen.' },
  { f: 'Du lädst den Hund zu einer Interaktion ein, aber er wollte gerade schlafen. Wie handelst du richtig?', a: ['Den Hund trotzdem holen, die Klasse wartet', 'Keine Interaktion machen und es den Schülern erklären – der Hund muss freiwillig mitmachen', 'Den Hund mit Futter locken, bis er kommt', 'Die Interaktion verkürzen, aber durchziehen'], k: 1, e: 'Den Hund einladen und darauf achten, ob er möchte. Wollte er eigentlich schlafen, keine Interaktion machen und es den Schülern erklären – Schulhunde dürfen nicht instrumentalisiert werden.' },
  { f: 'Du planst eine Interaktion. Wie verhinderst du, dass der Hund umzingelt wird?', a: ['Die Kinder im Kreis um den Hund setzen', 'Genug Abstand zwischen Hund und allen Beteiligten lassen, keine Kreisbildung – der Hund muss immer gehen können', 'Den Hund anbinden', 'Möglichst viele Kinder gleichzeitig'], k: 1, e: 'Genug Abstand zwischen Hund und Beteiligten, keine Kreisbildung zulassen – der Hund muss immer gehen können, wenn es ihm zu viel ist.' }
],

'recht-konzept': [
  { f: 'Eine Kollegin fragt, welches Regelwerk den Hundeeinsatz in bayerischen Schulen verbindlich regelt. Was antwortest du?', a: ['Das Tierschutzgesetz allein', 'Die RiSU (Richtlinie zur Sicherheit im Unterricht) der KMK – Punkt II–3.1', 'Die Hundeverordnung Bayern', 'Das Schulhundweb'], k: 1, e: 'Die RiSU der Kultusministerkonferenz enthält in Punkt II–3.1 „Umgang mit Tieren“ Ausführungen zum Hundeeinsatz; in Bayern ist sie eine verbindliche Vorschrift für alle Schulen.' },
  { f: 'Wer ist an deiner Schule für die Einhaltung der RiSU vor Ort verantwortlich?', a: ['Das Kultusministerium', 'Die Schulleitung', 'Die Eltern', 'Der Hausmeister'], k: 1, e: 'Für die Einhaltung der RiSU – auch im Bereich der HuPäSch – sind die Schulleitungen vor Ort verantwortlich.' },
  { f: 'Darf eine Vertretungslehrkraft den Schulhund kurz „mitbetreuen", wenn du raus musst? Unter wessen Aufsicht darf der Hund mit Schülern eingesetzt werden?', a: ['Unter Aufsicht eines beliebigen Erwachsenen', 'Ausschließlich unter ständiger Aufsicht der Hundeführerin / des Hundeführers', 'Schüler ab 16 dürfen allein aufpassen', 'Eine Aufsicht ist nicht nötig'], k: 1, e: 'Der Einsatz erfolgt ausschließlich unter ständiger Aufsicht des Hundeführers – ein Einsatz ohne ihn ist nicht zulässig.' },
  { f: 'Du planst die Tierarzttermine für deinen Schulhund. Wie oft empfiehlt die TVT eine tierärztliche Vorsorgeuntersuchung?', a: ['1× pro Jahr', '2× pro Jahr', '4× pro Jahr', 'Nur bei Krankheit'], k: 2, e: 'Die TVT empfiehlt eine regelmäßige (4×/Jahr) tierärztliche Vorsorgeuntersuchung sowie Tierarztbesuche bei Krankheitsanzeichen.' },
  { f: 'Du erstellst den Einsatzplan deines Hundes. Welche maximale Einsatzhäufigkeit empfiehlt die TVT?', a: ['Täglich, bis zu 8 Stunden', '2–3× pro Woche, max. 1 Einsatz/Tag für max. 3–4 Stunden', '1× pro Monat', '5× pro Woche, 2 Einsätze täglich'], k: 1, e: 'Max. 2–3×/Woche (abhängig von Einsatzform, Alter, Konstitution), max. 1 Einsatz/Tag für max. 3–4 Stunden.' },
  { f: 'Dein Hund ist 14 Monate alt. Ab welchem Alter sollte ein Hund laut TVT eingesetzt werden?', a: ['Ab 6 Monaten', 'Nach Erreichen der sozialen Reife mit 2–3 Jahren (empfohlen: älter als 18 Monate)', 'Ab dem 5. Lebensjahr', 'Das Alter spielt keine Rolle'], k: 1, e: 'Mindestalter: nach Erreichen der sozialen Reife mit 2–3 Jahren, mindestens in körperlich und geistig ausgereiftem Entwicklungszustand (empfohlen: älter als 18 Monate).' },
  { f: 'Du begründest im Kollegium, warum Schulhundarbeit so sorgfältig sein muss. Wie viele Sitzungen stufte die LMU-Studie 2022 als problematisch ein?', a: ['10 %', '25,9 %', '50 %', '75 %'], k: 2, e: '50 % problematisch, 25,9 % kritisch, nur 24,1 % harmlos. Nur 40,7 % der Teams hatten eine Schulhundausbildung; in 64,8 % der Klassen wurde der Hund umzingelt.' },
  { f: 'Was fordert die LMU-Studie für jede Schüler-Hund-Interaktion?', a: ['Mehr Tricks', 'Freiwilligkeit des Hundes, Reflexion durch den Besitzer, Reaktion auf (subtile) Anzeichen wie Entzugsverhalten', 'Längere Einsatzzeiten', 'Weniger Dokumentation'], k: 1, e: 'Jede Interaktion muss auf Freiwilligkeit des Hundes basieren und reflektiert werden; der Besitzer muss auf jedes Hundeanzeichen, v. a. Entzugsverhalten, reagieren.' },
  { f: 'Im Hygieneplan thematisierst du die Fütterung. Bei wie viel Prozent der gebarften Hunde fand die kanadische Studie Salmonellen?', a: ['5 %', '15 %', '30 %', '60 %'], k: 2, e: 'Bei 30 % der gebarften Hunde wurden Salmonellen gefunden, ohne dass die Hunde selbst erkrankten – eine Infektionsquelle für Kontaktpersonen.' },
  { f: 'Du legst die Reinigung im Hygieneplan fest. Bei welcher Temperatur wird der Hundenapf täglich gereinigt?', a: ['30 °C', '40 °C', 'mind. 60 °C', '90 °C'], k: 2, e: 'Der Hundenapf wird täglich mit mindestens 60 °C warmem Wasser gereinigt und getrocknet; Stoffzubehör wird wöchentlich bei mind. 60 °C gewaschen.' },
  { f: 'In deiner Lerngruppe stellt sich heraus, dass ein Kind eine Hundeallergie hat. Was gilt?', a: ['Der Einsatz findet trotzdem statt', 'Grundsätzlich kein Einsatz – Ausnahmen nur mit schriftlicher Zustimmung der Sorgeberechtigten', 'Das Kind muss in eine andere Klasse', 'Der Hund trägt dann einen Anzug'], k: 1, e: 'Grundsätzlich erfolgt kein Einsatz bei Allergie in der Lerngruppe. Ausnahmen nur, wenn die Sorgeberechtigten es wünschen und schriftlich zustimmen.' },
  { f: 'Du legst das Schulhundkonzept an. Welche Inhalte gehören laut Skript hinein?', a: ['Nur ein Foto des Hundes', 'Team, Schule, RiSU, Wirkmechanismen, Regeln, Einsatzkonzept, Klassenzimmer, Notfallplan, Hygieneplan', 'Nur der Stundenplan', 'Nur die Telefonnummer der Schulleitung'], k: 1, e: 'Das Schulhundkonzept enthält u. a.: Team, Einsatzschule, RiSU, Wirkmechanismen, Schulhundregeln, individuelles Einsatzkonzept, Klassenzimmer, Notfallplan und Hygieneplan.' }
],

gewoehnung: [
  { f: 'Du nimmst deinen Hund das erste Mal mit in die Schule. Wann findet echte Gewöhnung statt?', a: ['Wenn der Hund stark auf den Reiz reagiert', 'Wenn der Hund dem Reiz so ausgesetzt wird, dass er neutral oder minimalst darauf reagiert', 'Wenn der Hund den Reiz täglich erlebt', 'Wenn der Hund müde ist'], k: 1, e: 'Gewöhnung erfolgt nur, wenn der Hund einem Reiz so ausgesetzt wird, dass er neutral oder minimalst darauf reagiert – sonst droht Sensibilisierung.' },
  { f: 'Du planst die Schulgewöhnung in kleinen Schritten. Wie lauten die ersten beiden Schritte?', a: ['Eigener Unterricht → Pausenhof', 'Besuche des leeren Schulgebäudes → Besuch des „belebteren“ Schulgebäudes', 'Schulfest → Unterricht', 'Klassenzimmer → Turnhalle'], k: 1, e: 'Reihenfolge: leeres Schulgebäude → belebteres Gebäude → reguläre Unterrichtszeit → „trubeligere“ Zeiten → Stunde bei anderer Lehrkraft → eigener Unterricht.' },
  { f: 'Beim ersten Besuch im leeren Schulgebäude – worauf achtest du besonders?', a: ['Der Hund läuft frei durch alle Räume', 'Gassigang vorher; der Hund erkundet in seinem Tempo an lockerer Leine am Geschirr', 'Möglichst viele Kollegen begrüßen den Hund', 'Der Hund bleibt im Auto'], k: 1, e: 'Gassigang vor dem Schulbesuch; der Hund soll sich sicher fühlen und das Gebäude in seinem Tempo in Ruhe erkunden (lockere Leine am Geschirr).' },
  { f: 'Ihr seid in einer trubeligen Schulsituation. Wann solltest du die Schule wieder verlassen?', a: ['Wenn der Hund deutlich gestresst ist', 'BEVOR der Hund Stresszeichen zeigt', 'Nach exakt einer Stunde', 'Wenn der Hund einschläft'], k: 1, e: 'Der Hund sollte trubeligeren Situationen nur kurz ausgesetzt werden, und die Schule sollte verlassen werden, bevor er Stresszeichen zeigt.' },
  { f: 'Wo besprichst du die Schulhundregeln mit den Kindern?', a: ['Beim ersten Hundebesuch', 'In Unterrichtsstunden OHNE Hund', 'Auf dem Pausenhof mit Hund', 'Nur schriftlich per Brief'], k: 1, e: 'Die Besprechung der Schulhundregeln erfolgt in den Unterrichtsstunden ohne Hund.' },
  { f: 'Du arbeitest die Einführungs-Checkliste ab. Was gehört dazu?', a: ['Nur ein Foto des Hundes', 'U. a. Gesundheitscheck, Genehmigung der Schulleitung, Konzept + Hygieneplan, Haftpflicht mit Schulhund-Zusatz, Eltern-Info mit Allergieabfrage, Schulhundordner', 'Nur die Zustimmung der Klasse', 'Ein Eignungstest beim Hundeverein'], k: 1, e: 'Die Checkliste umfasst: Gesundheitscheck, Gespräch + Genehmigung der Schulleitung, Schulhundkonzept & Hygieneplan, Haftpflicht mit Zusatz, Gewöhnung, Eltern-/Schülerinfo mit Allergieabfrage, Schulhundordner, Verhaltensregeln.' },
  { f: 'Im Klassenzimmer steht eine verschließbare Hundebox. Wofür ist sie da?', a: ['Um unerwünschtes Verhalten zu „managen“', 'Für Notfälle – der Hund kann schnell aus der Situation geschickt und kurz geschützt werden', 'Als dauerhafter Schlafplatz', 'Für den Transport'], k: 1, e: 'Die Box ist für Notfälle (Schlägerei, Erbrochenes, giftige Lebensmittel, medizinischer Notfall) – NICHT um den Hund einzusperren und Verhalten zu „managen“.' },
  { f: 'Dein Hund liegt in seiner Ruhezone im Klassenzimmer. Welche Regel gilt für diese Zone?', a: ['Dort dürfen Kinder ihn leise streicheln', 'Dort darf er niemals gestört werden – die Zone „gehört“ nur dem Hund', 'Sie wird täglich umgestellt', 'Sie ist nur für den Winter'], k: 1, e: 'Wenn der Hund in seiner Ruhezone ist, darf er dort niemals von Schülern oder Kollegen gestört werden. Diese Zone gehört nur dem Hund.' },
  { f: 'Du legst Arbeitsteppiche im Klassenzimmer aus. Warum sind sie so wichtig?', a: ['Als Dekoration', 'Hunde rutschen auf Schulböden fast immer; der Teppich strukturiert und ritualisiert zudem das Setting', 'Damit der Boden sauber bleibt', 'Als Schlafplatz'], k: 1, e: 'Die Teppiche sind sehr wichtig, da Hunde auf Schulböden fast immer rutschen. Zusätzlich helfen sie, das Setting zu strukturieren und zu ritualisieren – das gibt allen Sicherheit.' },
  { f: 'Du möchtest ein Hundegitter an der Klassenzimmertür anbringen. Was ist unbedingt zu beachten?', a: ['Es muss aus Holz sein', 'Keine Fluchtwege behindern oder versperren', 'Es muss abschließbar sein', 'Es bleibt dauerhaft montiert'], k: 1, e: 'Bitte individuell absprechen und die örtlichen Gegebenheiten prüfen, damit keine Fluchtwege behindert und versperrt werden.' },
  { f: 'Dein Hund soll die Schule nicht nur als aufregenden Ort erleben. Worauf achtest du bei der Gewöhnung?', a: ['Möglichst viel „Action" und Begrüßungen', 'Der Hund soll die Schule nicht als reinen „Party-/Actionort“ kennenlernen, sondern dort auch zur Ruhe kommen', 'Den Hund von allen Kindern begrüßen lassen', 'Nur in den Pausen üben'], k: 1, e: 'Der Hund soll die Schule nicht als reinen „Party-/Actionort“ kennenlernen, sondern dort auch gut zur Ruhe kommen – im Idealfall verbindet er sie mit einem entspannten Gefühl.' }
]

};

// ──────────────────────────────────────────────────────────────────────
// Zusätzliche, schwierigere Prüfungsfragen  (werden automatisch mit d:3
// = „schwer" markiert). Sie heben das Niveau der Abschlussprüfung und
// sorgen für mehr Abwechslung. Format wie oben (f / a / k / e).
// ──────────────────────────────────────────────────────────────────────
(function () {
  var SCHWER = {

    grundlagen: [
      { f: 'Insgesamt lebten 2024 rund 33,9 Mio. Heimtiere in Deutschland. In wie viel Prozent der Familien MIT KINDERN lebt ein Heimtier?', a: ['44 %', '55 %', '68 %', '80 %'], k: 2, e: '44 % aller Haushalte besitzen ein Heimtier – aber in 68 % aller Familien mit Kindern lebt ein Heimtier.' },
      { f: 'Welche Aussage zur Haltung gegenüber Hunden in muslimischen Ländern ist FALSCH?', a: ['Die zwiegespaltene Einstellung geht laut Prof.in Dr. Sarra Tlili auf 4 islamische Rechtsschulen zurück', 'Dr. Khaled Abou El Fadl fand heraus, dass zu Mohammeds Lebzeiten Hunde in Medina frei herumliefen', 'Aus Sure 6, Vers 38 wird abgeleitet, dass Tiere gut behandelt werden sollen', 'Der Koran verbietet das Halten von Hunden ausnahmslos'], k: 3, e: 'Die Einstellung ist gerade NICHT einheitlich ablehnend, sondern zwiegespalten. Zu Mohammeds Zeit liefen Hunde in Medina frei umher und betraten sogar die Moschee.' },
      { f: 'In fast allen Bundesländern gehört das Wort „Hund“ zum Grundwortschatz welcher Jahrgangsstufen?', a: ['Kindergarten / Vorschule', '1. und 2. Jahrgangsstufe', '3. und 4. Jahrgangsstufe', '5. und 6. Jahrgangsstufe'], k: 1, e: '„Hund“ gehört in fast allen Bundesländern zum Grundwortschatz der 1. und 2. Jahrgangsstufe.' }
    ],

    begriffe: [
      { f: 'Ein Hund besucht mit seinem Besitzer regelmäßig ein Altenheim und trägt zum Wohlbefinden der Bewohner bei. Um welchen Hund handelt es sich?', a: ['Schulbesuchshund', 'Besuchshund', 'Therapiebegleithund', 'Assistenzhund'], k: 1, e: 'Besuchshunde begleiten Menschen OHNE therapeutische Ausbildung REGELMÄSSIG in Einrichtungen (Altenheime, Kinderheime). Schulbesuchshunde kommen meist nur einmalig in Schulen/Kindergärten.' },
      { f: 'Bringe die deutschen Schulhund-Meilensteine in die richtige zeitliche Reihenfolge.', a: ['Schulhundweb → „Hilfslehrer Hund“ → Freiwillige Selbstverpflichtung', '„Hilfslehrer Hund“ (2002) → Schulhundweb (2005) → Freiwillige Selbstverpflichtung (2012)', 'Freiwillige Selbstverpflichtung → Schulhundweb → „Hilfslehrer Hund“', '„Hilfslehrer Hund“ → Freiwillige Selbstverpflichtung → Schulhundweb'], k: 1, e: '2002 Artikel „Hilfslehrer Hund“, 2005 Schulhundweb, 2012 Freiwillige Selbstverpflichtung (2016 in „Selbstverpflichtung“ geändert), 2017 Qualitätsnetzwerk Schulbegleithunde e.V.' },
      { f: 'Laut IAHAIO-Definition der TGP muss die Fachkraft u. a. adäquate Kenntnisse worüber besitzen?', a: ['Über die Rassegeschichte des Hundes', 'Über Verhalten, Bedürfnisse, Gesundheit und die Stress-Regulation des Tieres', 'Über die Buchführung des Vereins', 'Über die Lehrpläne aller Schularten'], k: 1, e: 'Die IAHAIO verlangt adäquate Kenntnisse über Verhalten, Bedürfnisse, Gesundheit und die Indikatoren/Regulation von Stress der beteiligten Tiere.' }
    ],

    bindung: [
      { f: 'In Bowlbys Bindungstheorie: Was bezeichnet „bonding“ (im Gegensatz zu „attachment“)?', a: ['Das Bindungsverhalten des Säuglings', 'Das elterliche Fürsorgeverhalten', 'Die Bindung zwischen zwei Hunden', 'Die Loslösung nach der Pubertät'], k: 1, e: '„attachment“ = Bindungsverhalten des Säuglings, „bonding“ = elterliches Fürsorgeverhalten.' },
      { f: 'Welche der folgenden gehört NICHT zu den drei Merkmalen, an denen man laut Definition eine Bindung des Hundes erkennt?', a: ['Individuelles Erkennen des Menschen', 'Nutzung des Menschen als sichere Basis', 'Entspanntes Begrüßen nach stressbelasteter Trennung', 'Gehorsam auf alle Signale auch unter starker Ablenkung'], k: 3, e: 'Bindung zeigt sich an individuellem Erkennen, sicherer Basis (secure base effect) und entspanntem Begrüßen nach Trennung – nicht am Gehorsamslevel.' },
      { f: 'Warum sind Strafregeln laut Skript „im wahren Leben nicht einhaltbar“?', a: ['Weil Strafe nur bei willentlich steuerbarem Verhalten und nur IMMER, SOFORT und HEFTIG wirken dürfte', 'Weil Hunde Strafe grundsätzlich nicht wahrnehmen', 'Weil Strafe gesetzlich verboten ist', 'Weil Strafe das Lernen beschleunigt'], k: 0, e: 'Strafe dürfte nur bei willentlich steuerbarem Verhalten erfolgen – und IMMER, SOFORT, HEFTIG, mit Ankündigung und Alternative. Das ist nicht einhaltbar; zudem belastet Strafe das Bindungskonto (Fehlverknüpfungsgefahr).' }
    ],

    wirkmechanismen: [
      { f: 'Welche Wirkung hat Oxytocin laut Skript NICHT?', a: ['Senkung von Blutdruck und Herzfrequenz für mehrere Stunden', 'Verringerung des Kortisolspiegels', 'Entzündungshemmung und Heraufsetzung der Schmerzgrenze', 'Steigerung der Aggressionsbereitschaft'], k: 3, e: 'Oxytocin senkt u. a. Kortisol, Blutdruck/Herzfrequenz (für Stunden), wirkt entzündungshemmend und hebt die Schmerzgrenze – es VERRINGERT Aggressivität, steigert sie nicht.' },
      { f: 'Zu welchem der drei Wirkungsbereiche zählt die „Hemmung von Angst“?', a: ['Soziale Wirkung', 'Psychologische Wirkung', 'Physiologische Wirkung', 'Keinem – das ist keine belegte Wirkung'], k: 1, e: 'Angsthemmung zählt zu den PSYCHOLOGISCHEN Wirkungen (wie Motivation, Selbstwirksamkeit, Trost). Physiologisch = Puls/Blutdruck/Oxytocin; sozial = Kommunikation/Aggressionsminderung.' },
      { f: 'Antonovskys Kohärenzgefühl: „Vertrauen, dass es sinnvoll ist, sich einer Aufgabe aktiv und emotional zu stellen“ – welcher Bereich ist das?', a: ['Verstehbarkeit', 'Handhabbarkeit', 'Sinnhaftigkeit', 'Machbarkeit'], k: 2, e: 'Das ist die Sinnhaftigkeit. Verstehbarkeit = Anforderungen lassen sich strukturieren/erklären; Handhabbarkeit = es eröffnen sich Wege, Anforderungen zu meistern.' },
      { f: 'Was bedeutet es für die Praxis, dass Spiegelneuronen „keine Selbstläufer“ sind?', a: ['Hunde verstehen uns automatisch immer richtig', 'Die Zeichen der Hunde können falsch entschlüsselt werden – Fehlinterpretationen sind möglich', 'Spiegelneuronen wirken nur bei Welpen', 'Man muss Spiegelneuronen erst antrainieren'], k: 1, e: 'Die Mechanismen sind keine Selbstläufer: Die Zeichen der Hunde können falsch entschlüsselt werden. Deshalb gemeinsame Aktivitäten und gegenseitiges Kennenlernen fördern.' }
    ],

    lernverhalten: [
      { f: 'Ein Hund zieht an der Leine; sobald er nachgibt, lässt der unangenehme Leinenzug nach. Welcher Quadrant und welche Emotion?', a: ['Positive Strafe – Angst', 'Negative Belohnung – Erleichterung', 'Negative Strafe – Frustration', 'Positive Belohnung – Freude'], k: 1, e: 'Etwas Unangenehmes (Leinenzug) hört auf = negative Belohnung/Verstärkung, Emotion: Erleichterung.' },
      { f: 'Beim Spielen mit Artgenossen zwickt ein Welpe zu fest – das Spiel wird sofort beendet. Welcher Quadrant ist das?', a: ['Positive Strafe', 'Negative Strafe', 'Negative Belohnung', 'Positive Belohnung'], k: 1, e: 'Etwas Angenehmes (das Spiel) hört auf = negative Strafe; Emotion: Frustration/Erfolgslosigkeit.' },
      { f: 'Wann hat ein Hund laut Skript WIRKLICH durch Nachahmung gelernt?', a: ['Wenn er einem anderen Hund nachläuft', 'Wenn er allein aufgrund der Beobachtung – ohne eigene Vorerfahrung – etwas bisher nicht Gekonntes tut', 'Wenn er ein Verhalten nach vielen eigenen Versuchen zeigt', 'Wenn er auf ein Signal reagiert'], k: 1, e: 'Echte Nachahmung liegt nur vor, wenn der Hund allein durch Beobachtung – ohne vorherige eigene Erfahrung – etwas nicht Angeborenes tut, das er vorher nicht konnte (z. B. „Do as I do“).' },
      { f: 'Ein unausgebildeter Hund wird in eine laute Menschenmenge gestellt „damit er sich gewöhnt“ und erstarrt regungslos. Was passiert hier am ehesten?', a: ['Erfolgreiche Habituation', 'Flooding (Resignation) – keine Gewöhnung', 'Klassische Konditionierung', 'Premack-Effekt'], k: 1, e: 'Reizüberflutung ohne Entkommen führt zu Flooding/Resignation – das ist KEINE Gewöhnung. Habituation erfolgt nur, wenn der Hund neutral/minimal reagiert.' }
    ],

    markertraining: [
      { f: 'Beim Aufbau des Markerworts (klassische Konditionierung): Was ist das Futter und was der Click VOR dem Training?', a: ['Futter = neutraler Reiz, Click = konditionierter Reiz', 'Futter = unkonditionierter Reiz, Click = neutraler Reiz', 'Beide sind konditionierte Reize', 'Futter = konditionierter, Click = unkonditionierter Reiz'], k: 1, e: 'Futter ist der unkonditionierte Reiz, der Click zunächst ein neutraler Reiz – nach dem Training wird der Click zum konditionierten Reiz.' },
      { f: 'Welche Aussage zum Markersignal ist korrekt?', a: ['Das Markersignal IST die Belohnung', 'Das Markersignal kündigt eine Belohnung an – die Belohnung kommt erst danach', 'Nach dem Marker darf die Belohnung auch mal ausbleiben', 'Das Markersignal wird gleichzeitig mit dem Futter gegeben'], k: 1, e: 'Der Marker kündigt punktgenau eine Belohnung an; die Belohnung folgt unmittelbar DANACH und muss IMMER folgen – auch bei „falschem“ Click.' },
      { f: 'In welcher Reihenfolge läuft die spätere Signaleinführung (Hörzeichen) ab?', a: ['Verhalten → Signal → Marker', 'Signal sagen → Hund führt Verhalten aus → markern & belohnen', 'Marker → Signal → Verhalten', 'Signal und Verhalten gleichzeitig, dann Belohnung'], k: 1, e: 'Erst wenn das Verhalten zuverlässig gezeigt wird: 1. neues Signal sagen, 2. Hund führt Verhalten aus, 3. markern und belohnen.' }
    ],

    belohnungen: [
      { f: 'Ordne korrekt zu: „Ableinen und zu Hundefreunden rennen lassen“ ist eine ...', a: ['Sozialkontakt-Belohnung', 'Umweltbelohnung', 'Belohnung über ein gern gezeigtes Signal', 'Suchaufgabe'], k: 1, e: 'Ableinen, Schnüffeln, Buddeln, zu Hundefreunden rennen, Baden – das sind Umweltbelohnungen. Sozialkontakt = Loben/Streicheln/Kraulen.' },
      { f: 'Ein Hund bricht in Hetzmotivation eine Verfolgung ab und kommt auf Rückruf. Welche Belohnung passt zur Bedürfnislage am besten?', a: ['Ein Stück Trockenfutter aus der Hand', 'Ruhiges Streicheln', 'Einen Ball hetzen oder einen Felldummy geworfen bekommen', 'Auf der Decke ablegen'], k: 2, e: 'Der Hund war in Hetzmotivation – passend ist eine Belohnung, die diese bedient: Ball hetzen oder Hasenfelldummy werfen.' },
      { f: 'Welche zwei Grundregeln nennt das Skript fürs Belohnen?', a: ['Immer Futter & immer sofort', 'Variabel sein & der momentanen Bedürfnislage entsprechen', 'Selten & dafür besonders groß', 'Nur nach perfektem Verhalten & nur mit Spielzeug'], k: 1, e: 'Belohnungen sollen variabel sein und der momentanen Bedürfnislage des Hundes so gut wie möglich entsprechen.' }
    ],

    signale: [
      { f: 'Beim Steigern von Rückruf oder Bleib gilt die Faustregel ...', a: ['Distanz und Ablenkung gemeinsam erhöhen, um Zeit zu sparen', 'Immer nur EIN Kriterium gleichzeitig steigern (Distanz ODER Ablenkung)', 'Zuerst immer die Ablenkung maximieren', 'Kriterien spielen keine Rolle'], k: 1, e: 'Es wird immer nur ein Kriterium gesteigert – entweder Distanz oder Ablenkung, nie beides gleichzeitig.' },
      { f: 'Was passiert, wenn man die Sitzdose auch zum Schimpfen oder Zwingen einsetzt?', a: ['Sie wirkt dann schneller', 'Sie funktioniert nicht mehr – sie darf ausschließlich Gutes ankündigen', 'Der Hund lernt dadurch mehr Impulskontrolle', 'Nichts, das ist erlaubt'], k: 1, e: 'Die Sitzdose kündigt ausschließlich Gutes an. Wird sie mit Schimpfen/Zwang verknüpft, funktioniert sie nicht mehr.' },
      { f: 'Warum sollte man den Hund beim „Bleib“-Training möglichst NICHT aus dem Sitz abrufen?', a: ['Weil er sonst das Sitzsignal vergisst', 'Weil er sonst in steter Erwartung ist, wann er endlich loslaufen darf, statt ruhig zu warten', 'Weil Abrufen das Bleib beschleunigt', 'Weil der Rückruf dadurch kaputtgeht'], k: 1, e: 'Wird er aus dem Sitz abgerufen, wartet er nur gespannt aufs Loslaufen. Ruhiges Warten lernt er, wenn der Mensch zu ihm zurückkommt und dort belohnt.' },
      { f: 'Worauf beruht der Aufbau des Signals „Aus“ – und worauf muss man achten?', a: ['Auf Wegnehmen; der Hund muss lernen zu verzichten', 'Auf dem Tauschprinzip (Loslassen lohnt sich) – Achtung: kostet viel Impulskontrolle', 'Auf Strafe bei Nichtloslassen', 'Auf Ignorieren des Hundes'], k: 1, e: 'Der Hund lernt über das Tauschprinzip, dass Loslassen sich lohnt und ihm das Objekt nicht (sofort) weggenommen wird. Das Training kostet viel Impulskontrolle.' }
    ],

    stress: [
      { f: 'Welche Aussage über Eustress ist korrekt?', a: ['Eustress ist immer gesund und unbedenklich', 'Auch lang anhaltender Eustress kann zu mentaler Erschöpfung bis zum Burnout führen', 'Eustress betrifft nur Menschen', 'Eustress entsteht nur bei Gefahr'], k: 1, e: 'Eustress ist eher positiver Stress – aber lang anhaltend kann auch er zu mentaler Erschöpfung bis hin zum Burnout führen.' },
      { f: 'In welcher Phase der Stressreaktion werden Adrenalin, Noradrenalin und Cortisol ausgeschüttet?', a: ['Widerstandsphase', 'Alarmreaktionsphase', 'Erschöpfungsphase', 'Erholungsphase'], k: 1, e: 'In der ersten Phase – der Alarmreaktionsphase – versetzt die Ausschüttung von Adrenalin, Noradrenalin und Cortisol den Körper in Kampf-/Fluchtbereitschaft.' },
      { f: 'Zu welcher Stressoren-Kategorie zählt der „Entzug von Reizen (Deprivation)“?', a: ['Körperliche Stressoren', 'Äußere Stressoren', 'Psychische Stressoren', 'Soziale Stressoren'], k: 1, e: 'Reizüberflutung UND Deprivation (Reizentzug) zählen zu den äußeren Stressoren.' },
      { f: 'Ein Hund gähnt, leckt sich über die Schnauze und wendet dann den Blick ab. Wie nennt man diese Abfolge?', a: ['Übersprungshandlung', 'Beschwichtigungskette', 'Stressgesicht', 'Demutsgeste'], k: 1, e: 'Mehrere Beschwichtigungssignale hintereinander nennt man Beschwichtigungskette. Sie wirken beruhigend/aggressionsmindernd, auch Menschen gegenüber.' }
    ],

    koerpersprache: [
      { f: 'Ein Hund wedelt mit schmaler Amplitude und sehr schneller Frequenz. Was bedeutet das am ehesten?', a: ['Große Freude', 'Hohe Körperspannung', 'Einladung zum Spiel', 'Tiefe Entspannung'], k: 1, e: 'Schmales, schnelles Wedeln deutet auf hohe Körperspannung hin. Entspanntes Wedeln ist breit/schlackernd; kreisende „Propeller“-Bewegung = Interessenkonflikt.' },
      { f: 'Ein Hund droht mit abgesenktem Kopf, eingeklemmter Rute und abgeducktem Körper. Wie ist das einzuordnen?', a: ['Sicheres (offensives) Drohen', 'Unsicheres (defensives) Drohen', 'Aktive Demut', 'Spielaufforderung'], k: 1, e: 'Nach hinten/unten gerichtete Signale (Kopf abgesenkt, Rute eingeklemmt, abgeduckt) = unsicheres, defensives Drohen. Offensiv = alles nach vorne/oben, aufrechter steifer Stand.' },
      { f: 'Ein angeleinter Hund kann vor einem Auslöser nicht fliehen. Was sagt das Konzept der 4 F voraus?', a: ['Er beruhigt sich automatisch', 'Er kann auf eine andere Strategie der 4 F ausweichen – z. B. Angriff (Fight)', 'Er friert dauerhaft ein', 'Er zeigt Spielverhalten'], k: 1, e: 'Wird die Flucht (Flight) verhindert – etwa durch die Leine – können andere Strategien der 4 F greifen, z. B. Fight. Nach dem Freeze ist grundsätzlich jedes Verhalten möglich.' },
      { f: 'Was ist beim objektiven Lesen von Hundeverhalten die richtige Reihenfolge?', a: ['Interpretieren → Beobachten → Beschreiben → Diskutieren', 'Beobachten → Beschreiben → Interpretieren → Diskutieren', 'Diskutieren → Beschreiben → Beobachten → Interpretieren', 'Beschreiben → Interpretieren → Diskutieren → Beobachten'], k: 1, e: 'Erst beobachten und beschreiben, dann interpretieren und diskutieren – sonst interpretiert man vorschnell.' }
    ],

    'verhalten-schule': [
      { f: 'Warum löst ein „Nein“ unerwünschtes Verhalten laut Skript nicht?', a: ['Hunde hören „Nein“ nicht', 'Es unterdrückt das Verhalten nur – wie ein zugeschweißter Topf, der irgendwann überkocht', 'Es ist zu kurz, um wirksam zu sein', 'Es wirkt nur bei Welpen'], k: 1, e: '„Nein“ unterdrückt nur; Unterdrücktes kommt an anderer Stelle hervor (Bild vom zugeschweißten kochenden Topf). Besser zeigen, was der Hund STATTDESSEN tun soll.' },
      { f: 'Ein Hund bellt, um Aufmerksamkeit zu bekommen, und wird daraufhin angeschimpft. Was kann passieren?', a: ['Das Bellen hört sofort dauerhaft auf', 'Das Schimpfen wirkt als Verstärkung, weil es Aufmerksamkeit ist', 'Der Hund bekommt Angst und vergisst das Verhalten', 'Nichts'], k: 1, e: 'Schimpfen kann eine Verstärkung sein, wenn der Hund Aufmerksamkeit möchte und durch das Schimpfen genau diese erhält.' },
      { f: 'Welche Aussage über „Management“ trifft zu?', a: ['Management ersetzt das Training vollständig', 'Management verändert die Rahmenbedingungen und ersetzt KEIN Training, ist aber wichtige Begleitmaßnahme', 'Management ist eine Bestrafungsmethode', 'Management bedeutet, den Hund einzusperren'], k: 1, e: 'Management gestaltet die Situation so, dass sich der Hund „wie ein Musterschüler“ verhalten kann. Es ersetzt kein Training, schafft aber die Basis dafür.' },
      { f: 'Wie ist mit schulischen Ausnahmesituationen wie einem Feueralarm umzugehen?', a: ['Den Hund langsam daran gewöhnen', 'Der Hund sollte nicht dabei sein – solche Situationen sind nicht trainierbar (Management)', 'Mit besonders vielen Leckerlis arbeiten', 'Den Hund in der Box lassen und weitermachen'], k: 1, e: 'Ausnahmesituationen (Feueralarm, Bombenalarm ...) sind nicht trainierbar – der Hund sollte nicht dabei sein. Das fällt unter Management.' }
    ],

    'regeln-interaktionen': [
      { f: 'Welches Ergebnis lieferte die Bayerische Schulhundstudie 2022 NICHT?', a: ['Beliebte Interaktionen (z. B. Pfote geben) sind für Hunde oft unangenehm', 'Die 1-Kind-Regel wurde häufig nicht eingehalten', 'In zwei Dritteln der Einsätze gab es problematische Verhaltensweisen', 'Hunde lassen sich gerne umzingeln'], k: 3, e: 'Im Gegenteil: Hunde wurden häufig umzingelt, was problematisch ist. Beliebte Interaktionen sind oft unangenehm; die 1-Kind-Regel wurde oft missachtet; in 2/3 der Einsätze gab es problematisches Verhalten.' },
      { f: 'Wie positioniert und verhält sich die Lehrkraft bei einer Interaktion richtig?', a: ['Hinter dem Hund, um ihn zu kontrollieren', 'So, dass der Hund stets Lehrkraft UND Schüler sieht; die Lehrkraft steht neben den Schülern, Kreisbildung wird vermieden', 'Mit dem Rücken zur Klasse', 'Sie überlässt die Interaktion ganz den Schülern'], k: 1, e: 'Der Hund wird so positioniert, dass er immer Lehrkraft und Schüler sieht; die Lehrkraft steht neben den Schülern (nicht hinter dem Hund), genug Abstand, keine Kreisbildung – der Hund muss jederzeit gehen können.' },
      { f: 'Warum sollen mit dem Schulhund keine „Zirkusvorstellungen“ gemacht werden?', a: ['Tricks sind grundsätzlich verboten', 'Sonst entsteht ein unrealistisches Bild von Hunden – Nachmachen kann gefährlich werden; weniger ist mehr', 'Weil der Hund sonst zu berühmt wird', 'Weil Tricks zu teuer sind'], k: 1, e: 'Bei zu vielen ausgefallenen Interaktionen droht ein unrealistisches Bild von Hunden (Alltagshunde sind nicht so trainiert) – Nachmachen kann gefährlich werden. Weniger ist mehr.' }
    ],

    'recht-konzept': [
      { f: 'Welche Aussage zur RiSU ist korrekt?', a: ['Sie ist nur eine unverbindliche Empfehlung', 'In Bayern ist sie verbindlich; der Umgang mit Tieren steht in Punkt II–3.1; verantwortlich ist die Schulleitung', 'Verantwortlich für die Einhaltung ist allein das Kultusministerium', 'Sie regelt ausschließlich Chemieexperimente'], k: 1, e: 'Die RiSU ist in Bayern eine verbindliche Vorschrift für alle Schulen; der Umgang mit Tieren ist in Punkt II–3.1 geregelt; für die Einhaltung sind die Schulleitungen vor Ort verantwortlich.' },
      { f: 'Welche TVT-Empfehlung ist korrekt?', a: ['Vorsorge 1×/Jahr, Einsatz täglich bis 8 Std.', 'Vorsorge 4×/Jahr, Einsatz max. 2–3×/Woche, max. 1 Einsatz/Tag für max. 3–4 Std.', 'Vorsorge 2×/Jahr, Einsatz 5×/Woche', 'Vorsorge nur bei Krankheit, Einsatz unbegrenzt'], k: 1, e: 'TVT: tierärztliche Vorsorge 4×/Jahr; Einsatz max. 2–3×/Woche, max. 1 Einsatz pro Tag für max. 3–4 Stunden.' },
      { f: 'Wie viel Prozent der Sitzungen stufte die LMU-Studie 2022 als HARMLOS ein?', a: ['50 %', '25,9 %', '24,1 %', '64,8 %'], k: 2, e: 'Nur 24,1 % waren harmlos – 50 % problematisch, 25,9 % kritisch. In 64,8 % der Klassen wurde der Hund umzingelt; nur 40,7 % der Teams hatten eine Ausbildung.' },
      { f: 'In der Lerngruppe liegt eine Hundeallergie vor. Was gilt?', a: ['Der Einsatz findet uneingeschränkt statt', 'Grundsätzlich kein Einsatz – Ausnahme nur mit schriftlicher Zustimmung der Sorgeberechtigten', 'Das betroffene Kind muss die Klasse wechseln', 'Der Hund trägt einen Schutzanzug'], k: 1, e: 'Bei Allergie in der Lerngruppe erfolgt grundsätzlich kein Einsatz; eine Ausnahme ist nur mit schriftlicher Zustimmung der Sorgeberechtigten möglich.' }
    ],

    gewoehnung: [
      { f: 'Wie beginnt die Schulgewöhnung in der richtigen Reihenfolge?', a: ['Reguläre Unterrichtszeit → Pausen → leeres Gebäude', 'Leeres Schulgebäude → belebteres Gebäude → reguläre Unterrichtszeit', 'Eigener Unterricht → andere Lehrkraft → leeres Gebäude', 'Schulfest → Pausenhof → Klassenzimmer'], k: 1, e: 'Reihenfolge: leeres Gebäude → belebteres Gebäude → reguläre Unterrichtszeit → trubeligere Zeiten → Stunde bei anderer Lehrkraft → eigener Unterricht.' },
      { f: 'Wann sollte man die Schule beim Gewöhnungsbesuch verlassen – und warum?', a: ['Erst wenn der Hund deutlich gestresst ist, damit er es „durchhält“', 'BEVOR der Hund Stresszeichen zeigt – sonst droht Sensibilisierung statt Gewöhnung', 'Nach exakt 60 Minuten', 'Wenn der Hund eingeschlafen ist'], k: 1, e: 'Man verlässt die Schule, bevor der Hund Stresszeichen zeigt. Bei zu viel Stress findet keine Gewöhnung, sondern Sensibilisierung statt.' },
      { f: 'Wofür ist die verschließbare Hundebox im Klassenzimmer gedacht – und wofür NICHT?', a: ['Als dauerhafter Schlafplatz', 'Für Notfälle zum kurzen Schutz des Hundes – NICHT zum Einsperren / „Managen“ von Verhalten', 'Zum Bestrafen bei unerwünschtem Verhalten', 'Für den Transport im Auto'], k: 1, e: 'Die Box dient Notfällen (Schlägerei, Erbrochenes, Gift, medizinischer Notfall) zum kurzen Schutz – sie ist nicht dazu da, den Hund einzusperren und Verhalten zu managen.' },
      { f: 'Welche Besonderheit muss die Haftpflichtversicherung für den Schulhundeinsatz abdecken?', a: ['Nur Schäden zu Hause', 'Den Zusatz der Schulhundtätigkeit – inkl. Führung durch Fremdpersonen und Laufen ohne Leine in Klasse/Schulhof', 'Eine Lebensversicherung für den Hund', 'Nichts Besonderes'], k: 1, e: 'Nötig ist eine Hundehalterhaftpflicht mit Zusatz der Schulhundtätigkeit – inkl. punktueller Führung durch Kollegen/Schüler und Laufen ohne Leine in Klasse und Schulhof.' }
    ]

  };

  Object.keys(SCHWER).forEach(function (mid) {
    if (!window.QUIZ[mid]) window.QUIZ[mid] = [];
    SCHWER[mid].forEach(function (q) { q.d = 3; window.QUIZ[mid].push(q); });
  });
})();
